select count(*),sum(LO_REVENUE),sum(LO_SUPPLYCOST),sum(V_REVENUE) ,LO_PARTKEY ,SUPPLIER.S_CITY from SSB.V_LINEORDER LEFT JOIN SSB.SUPPLIER as SUPPLIER
ON V_LINEORDER.LO_SUPPKEY = SUPPLIER.S_SUPPKEY
where LO_PARTKEY in (1,20,300,4000,50000)
group by LO_PARTKEY, S_CITY
order by LO_PARTKEY