--https://github.com/Kyligence/KAP/issues/13863

SELECT KYLIN_SALES.PRICE,
KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME,
KYLIN_SALES.LSTG_FORMAT_NAME,
count(1),
count(DISTINCT KYLIN_SALES.PRICE + 1),
count(DISTINCT substring(KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME, 0, 4)),
count(DISTINCT CONCAT(KYLIN_SALES.LSTG_FORMAT_NAME, KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME))
FROM TEST_KYLIN_FACT as KYLIN_SALES
JOIN TEST_CATEGORY_GROUPINGS KYLIN_CATEGORY_GROUPINGS ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
GROUP BY KYLIN_SALES.PRICE,
KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME,
KYLIN_SALES.LSTG_FORMAT_NAME