--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT "SN"."N_NAME", SUM(l_extendedprice) "REVENUE"
FROM TPCH."LINEITEM"
INNER JOIN TPCH."ORDERS" ON "L_ORDERKEY" = "O_ORDERKEY"
INNER JOIN TPCH."CUSTOMER" ON "O_CUSTKEY" = "C_CUSTKEY"
INNER JOIN TPCH."NATION" "CN" ON "C_NATIONKEY" = "CN"."N_NATIONKEY"
INNER JOIN TPCH."SUPPLIER" ON "L_SUPPKEY" = "S_SUPPKEY"
INNER JOIN TPCH."NATION" "SN" ON "S_NATIONKEY" = "SN"."N_NATIONKEY"
INNER JOIN TPCH."REGION" ON "SN"."N_REGIONKEY" = "R_REGIONKEY"
WHERE "R_NAME" = 'A' AND "CN"."N_NAME" = "SN"."N_NAME" AND "O_ORDERDATE" >= '2010-01-01' AND "O_ORDERDATE" < '2010-01-02'
GROUP BY "SN"."N_NAME"
ORDER BY "REVENUE" DESC