--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
-- KE-25408
SELECT
CAST(CASE
		WHEN ABS(2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0)) + SQRT(4.0) * (ABS(TEST_KYLIN_FACT."LSTG_SITE_ID" - CAST(TEST_KYLIN_FACT."LSTG_SITE_ID" / 2.0 AS int) * 3.0) - 1.0) > 0.0 THEN SQRT(4.0) / 2.0
		ELSE 0.0
	END - CASE
		WHEN 2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0) < 0.0
			AND CASE
				WHEN ABS(2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0)) + SQRT(4.0) * (ABS(TEST_KYLIN_FACT."LSTG_SITE_ID" - CAST(TEST_KYLIN_FACT."LSTG_SITE_ID" / 2.0 AS int) * 3.0) - 1.0) > 0.0 THEN SQRT(4.0) / 2.0
				ELSE 0.0
			END > 0.0
		THEN SQRT(4.0)
		ELSE 0.0
	END + CAST(2 / SQRT(4.0) AS int) * SQRT(4.0) AS int) AS a from  TEST_KYLIN_FACT group by

CAST(CASE
		WHEN ABS(2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0)) + SQRT(4.0) * (ABS(TEST_KYLIN_FACT."LSTG_SITE_ID" - CAST(TEST_KYLIN_FACT."LSTG_SITE_ID" / 2.0 AS int) * 3.0) - 1.0) > 0.0 THEN SQRT(4.0) / 2.0
		ELSE 0.0
	END - CASE
		WHEN 2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0) < 0.0
			AND CASE
				WHEN ABS(2 - CAST(2 / SQRT(4.0) AS int) * SQRT(4.0)) + SQRT(4.0) * (ABS(TEST_KYLIN_FACT."LSTG_SITE_ID" - CAST(TEST_KYLIN_FACT."LSTG_SITE_ID" / 2.0 AS int) * 3.0) - 1.0) > 0.0 THEN SQRT(4.0) / 2.0
				ELSE 0.0
			END > 0.0
		THEN SQRT(4.0)
		ELSE 0.0
	END + CAST(2 / SQRT(4.0) AS int) * SQRT(4.0) AS int)