-- https://github.com/Kyligence/KAP/issues/5024

SELECT (CASE
WHEN ("CALCS"."DATE2" IS NULL) OR ("CALCS"."DATE3" IS NULL) THEN {fn CONVERT(NULL, SQL_DATE)}
WHEN "CALCS"."DATE2" < "CALCS"."DATE3" THEN "CALCS"."DATE2"
ELSE "CALCS"."DATE3" END) AS "TEMP_Test__2833295403__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE
WHEN ("CALCS"."DATE2" IS NULL) OR ("CALCS"."DATE3" IS NULL) THEN {fn CONVERT(NULL, SQL_DATE)}
WHEN "CALCS"."DATE2" < "CALCS"."DATE3" THEN "CALCS"."DATE2"
ELSE "CALCS"."DATE3" END)