SELECT {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__2721425198__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})}