SELECT {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATE2")}, SQL_VARCHAR)})} AS "TEMP_Test__4217154904__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATE2")}, SQL_VARCHAR)})}