SELECT {fn TIMESTAMPDIFF(SQL_TSI_HOUR,{fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)},"CALCS"."DATETIME0")} AS "TEMP_Test__487968357__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPDIFF(SQL_TSI_HOUR,{fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)},"CALCS"."DATETIME0")}