SELECT {fn SECOND({fn CONVERT({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)}, SQL_TIMESTAMP)})} AS "TEMP_Test__1396280131__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn SECOND({fn CONVERT({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)}, SQL_TIMESTAMP)})}