SELECT {fn LTRIM({fn CONVERT({fn DAYOFWEEK("CALCS"."DATE2")}, SQL_VARCHAR)})} AS "TEMP_Test__1696755361__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFWEEK("CALCS"."DATE2")}, SQL_VARCHAR)})}