SELECT {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn DAYOFWEEK("CALCS"."DATETIME0")} - 1)),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})} AS "TEMP_Test__2075598879__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn DAYOFWEEK("CALCS"."DATETIME0")} - 1)),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})}