SELECT {fn LTRIM({fn CONVERT({fn DAYOFWEEK("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__2227133008__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFWEEK("CALCS"."DATETIME0")}, SQL_VARCHAR)})}