SELECT {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATE2")}, SQL_VARCHAR)})} AS "TEMP_Test__1118529905__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATE2")}, SQL_VARCHAR)})}