SELECT {fn LTRIM({fn CONVERT({fn SECOND({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})} AS "TEMP_Test__1148110733__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn SECOND({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})}