SELECT (CASE WHEN ({fn LOCATE('IND',"CALCS"."STR1",1)} > 0) THEN 1 WHEN NOT ({fn LOCATE('IND',"CALCS"."STR1",1)} > 0) THEN 0 ELSE NULL END) AS "TEMP_Test__2889451650__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ({fn LOCATE('IND',"CALCS"."STR1",1)} > 0) THEN 1 WHEN NOT ({fn LOCATE('IND',"CALCS"."STR1",1)} > 0) THEN 0 ELSE NULL END)