SELECT {fn LTRIM({fn CONVERT({fn HOUR({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})} AS "TEMP_Test__3128330124__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn HOUR({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})}