SELECT {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATETIME0")} - 2), 7)})),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})} AS "TEMP_Test__3968681374__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATETIME0")} - 2), 7)})),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})}