SELECT {fn LTRIM({fn CONVERT({fn YEAR("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__2020086713__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn YEAR("CALCS"."DATETIME0")}, SQL_VARCHAR)})}