SELECT {fn LTRIM({fn CONVERT({fn MINUTE({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})} AS "TEMP_Test__1910386795__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn MINUTE({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}, SQL_VARCHAR)})}