SELECT {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATE2")} - 2), 7)})),{fn CONVERT("CALCS"."DATE2", SQL_DATE)})} AS "TEMP_Test__1283568777__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATE2")} - 2), 7)})),{fn CONVERT("CALCS"."DATE2", SQL_DATE)})}