SELECT {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__1792619982__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})}