--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

select
datetime0,
TIMESTAMPADD(YEAR, -6, datetime0) YEAR_ADD,
TIMESTAMPADD(MONTH, -6, datetime0) MONTH_ADD,
TIMESTAMPADD(QUARTER, -6, datetime0) QUARTER_ADD,
TIMESTAMPADD(SECOND, -6, datetime0) SECOND_ADD,
TIMESTAMPADD(MINUTE, -6, datetime0) MINUTE_ADD,
TIMESTAMPADD(HOUR, -6, datetime0) HOUR_ADD,
TIMESTAMPADD(DAY, -6, datetime0) DAY_ADD,
TIMESTAMPADD(WEEK, -6, datetime0) WEEK_ADD
from "TDVT"."CALCS"
ORDER BY datetime0
limit 2
