#!/bin/bash
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\pom.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\upgrade-old-config.sh
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\ServiceTestBase.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\controller\DiskResultCacheTest.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\controller\KapUserControllerTest.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\controller\RawTableControllerTest.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\controller\SequenceNodeOutputTest.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\test\java\io\kyligence\kap\rest\controller\topology\SequenceTopologyTest.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\webapp\WEB-INF\kylin-servlet.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\webapp\WEB-INF\web.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\resources\applicationContext.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\resources\ehcache-test.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\resources\ehcache.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\resources\kylinSecurity.xml
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\java\io\kyligence\kap\rest\DebugBCC.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\java\io\kyligence\kap\rest\DebugDeployCLI.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\java\io\kyligence\kap\rest\DebugResourceTool.java
sed -i -f upgrade-old-config.sed D:\git\kap-master\extensions\server\src\main\java\io\kyligence\kap\rest\DebugTomcat.java
