--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT "t2"."FULL_NAME" AS "FULL_NAME",
"t5"."X_measure__1" AS "avg_Calculation_578712577211949057_ok",
"t2"."X_measure__3" AS "avg_MARA_PROSPECTIVE_RISK_PRACTICE__copy__ok",
{fn CONVERT("t6"."X_measure__4", SQL_DOUBLE)} AS "avg_MARA_PROSPECTIVE_RISK_Provider__copy__ok"
FROM (   SELECT "t0"."FULL_NAME" AS "FULL_NAME",
AVG("t1"."X_measure__2") AS "X_measure__3"
FROM ( SELECT "Z_PROVDASH_UM_ED"."DEFAULT_PRACTICE" AS "DEFAULT_PRACTICE",
"Z_PROVDASH_UM_ED"."FULL_NAME" AS "FULL_NAME"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
WHERE ("Z_PROVDASH_UM_ED"."FULL_NAME" = 'JONATHAN AREND')
GROUP BY "Z_PROVDASH_UM_ED"."DEFAULT_PRACTICE", "Z_PROVDASH_UM_ED"."FULL_NAME") "t0"
INNER JOIN ( SELECT "Z_PROVDASH_UM_ED"."DEFAULT_PRACTICE" AS "DEFAULT_PRACTICE",
AVG("Z_PROVDASH_UM_ED"."MARA_PROSPECTIVE_RISK") AS "X_measure__2"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"     
GROUP BY "Z_PROVDASH_UM_ED"."DEFAULT_PRACTICE"   ) "t1" 
ON (("t0"."DEFAULT_PRACTICE" = "t1"."DEFAULT_PRACTICE") 
OR (("t0"."DEFAULT_PRACTICE" IS NULL) 
AND ("t1"."DEFAULT_PRACTICE" IS NULL)))   
GROUP BY "t0"."FULL_NAME" ) "t2"   
INNER JOIN (   SELECT "t3"."FULL_NAME" AS "FULL_NAME",     
{fn CONVERT("t4"."X_measure__0", SQL_DOUBLE)} AS "X_measure__1"   
FROM (     SELECT 'Source UM' AS "Calculation_59954192150036482", "Z_PROVDASH_UM_ED"."FULL_NAME" AS "FULL_NAME"     
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"     
WHERE ("Z_PROVDASH_UM_ED"."FULL_NAME" = 'JONATHAN AREND')     
GROUP BY "Z_PROVDASH_UM_ED"."FULL_NAME") "t3"     
INNER JOIN (  SELECT 'Source UM' AS "Calculation_59954192150036482", 
AVG("Z_PROVDASH_UM_ED"."MARA_PROSPECTIVE_RISK") AS "X_measure__0"     
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"     
HAVING (COUNT(1) > 0)) "t4" ON ("t3"."Calculation_59954192150036482" = "t4"."Calculation_59954192150036482") ) "t5" 
ON (("t2"."FULL_NAME" = "t5"."FULL_NAME") OR (("t2"."FULL_NAME" IS NULL) 
AND ("t5"."FULL_NAME" IS NULL)))   
INNER JOIN ( SELECT "Z_PROVDASH_UM_ED"."FULL_NAME" AS "FULL_NAME", 
AVG("Z_PROVDASH_UM_ED"."MARA_PROSPECTIVE_RISK") AS "X_measure__4"   
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"   
GROUP BY "Z_PROVDASH_UM_ED"."FULL_NAME" ) "t6" 
ON (("t2"."FULL_NAME" = "t6"."FULL_NAME") 
OR (("t2"."FULL_NAME" IS NULL) 
AND ("t6"."FULL_NAME" IS NULL)));