SELECT "Z_PROVDASH_UM_ED"."ZIP" AS "ZIP",
COUNT(DISTINCT "Z_PROVDASH_UM_ED"."MEMBER_ID") AS "ctd_MEMBER_ID_ok"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
WHERE ("Z_PROVDASH_UM_ED"."FULL_NAME" = 'JONATHAN AREND')
GROUP BY "Z_PROVDASH_UM_ED"."ZIP";