--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT "Z_PROVDASH_QPM_SCORE"."MEASURE_CODE" AS "MEASURE_CODE",
"Z_PROVDASH_QPM_SCORE"."MEASURE_DESC" AS "MEASURE_DESC",
AVG("Z_PROVDASH_QPM_SCORE"."BENCHMARK_RATE") AS "avg_BENCHMARK_RATE_ok",
AVG(("Z_PROVDASH_QPM_SCORE"."NPI_RATE" - "Z_PROVDASH_QPM_SCORE"."BENCHMARK_RATE")) AS "avg_Calculation_404761059420499972_ok",
AVG("Z_PROVDASH_QPM_SCORE"."NPI_RATE") AS "avg_NPI_RATE_ok"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_QPM_SCORE" "Z_PROVDASH_QPM_SCORE"
WHERE ("Z_PROVDASH_QPM_SCORE"."MEASURE_CODE" IN ('PQRS1', 'PQRS111', 'PQRS119', 'PQRS134', 'PQRS226'))
GROUP BY "Z_PROVDASH_QPM_SCORE"."MEASURE_CODE", "Z_PROVDASH_QPM_SCORE"."MEASURE_DESC"