SELECT {fn CONCAT({fn CONCAT("Z_PROVDASH_UM_ED"."PAYER", ' ')},
"Z_PROVDASH_UM_ED"."LOB")} AS "Calculation_886083264414601216",
"Z_PROVDASH_UM_ED"."LOB" AS "LOB",
"Z_PROVDASH_UM_ED"."PAYER" AS "PAYER",
COUNT(DISTINCT "Z_PROVDASH_UM_ED"."MEMBER_ID") AS "ctd_MEMBER_ID_ok"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
WHERE ("Z_PROVDASH_UM_ED"."FULL_NAME" = 'JONATHAN AREND')
GROUP BY {fn CONCAT({fn CONCAT("Z_PROVDASH_UM_ED"."PAYER", ' ')}, "Z_PROVDASH_UM_ED"."LOB")},
"Z_PROVDASH_UM_ED"."LOB",   "Z_PROVDASH_UM_ED"."PAYER";