-- KAP-9000
SELECT (CASE WHEN ("Z_PROVDASH_UM_ED"."COPD" = 1) THEN 'Yes' ELSE 'No ' END) AS "COPD__copy_"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
GROUP BY (CASE WHEN ("Z_PROVDASH_UM_ED"."COPD" = 1) THEN 'Yes' ELSE 'No ' END) ORDER BY 1 ASC;