--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT "t2"."X_measure__1" AS "avg_LOD_Network_Recapture__copy__ok",
"t1"."X_measure__3" AS "avg_LOD_Practice_HCC_RAF_Score__copy_2__ok",
"t4"."X_measure__5" AS "avg_LOD_Provider_RAF_Score__copy_2__ok"
FROM (   SELECT AVG("t0"."X_measure__2") AS "X_measure__3"
FROM (     SELECT "Z_360_HEAT"."PCP_PRACTICE" AS "PCP_PRACTICE",
AVG("Z_360_HEAT"."TOTAL_RAF_SCORE") AS "X_measure__2"
FROM "POPHEALTH_ANALYTICS"."Z_360_HEAT" "Z_360_HEAT"
GROUP BY "Z_360_HEAT"."PCP_PRACTICE") "t0"
HAVING (COUNT(1) > 0) ) "t1"
CROSS JOIN (   SELECT {fn CONVERT(AVG("Z_360_HEAT"."TOTAL_RAF_SCORE"), SQL_DOUBLE)} AS "X_measure__1"
FROM "POPHEALTH_ANALYTICS"."Z_360_HEAT" "Z_360_HEAT"
HAVING (COUNT(1) > 0) ) "t2"
CROSS JOIN (   SELECT AVG("t3"."X_measure__4") AS "X_measure__5"
FROM (     SELECT "Z_360_HEAT"."PCP_NAME" AS "PCP_NAME",
AVG("Z_360_HEAT"."TOTAL_RAF_SCORE") AS "X_measure__4"
FROM "POPHEALTH_ANALYTICS"."Z_360_HEAT" "Z_360_HEAT"
GROUP BY "Z_360_HEAT"."PCP_NAME") "t3"
HAVING (COUNT(1) > 0) ) "t4";