-- KAP-9000
SELECT (CASE WHEN ("Z_PROVDASH_UM_ED"."DIABETES" = 1)
THEN 'Yes' ELSE 'No ' END) AS "Calculation_540713452420141057"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
GROUP BY (CASE WHEN ("Z_PROVDASH_UM_ED"."DIABETES" = 1) THEN 'Yes' ELSE 'No ' END)
ORDER BY 1 ASC;