SELECT SUM(1) AS "COL"
FROM "POPHEALTH_ANALYTICS"."X_PROVIDER" "X_PROVIDER"
INNER JOIN "POPHEALTH_ANALYTICS"."Z_PROV_DASH_ATTRIBPROV" "Z_PROV_DASH_ATTRIBPROV"
ON ("X_PROVIDER"."NPI" = "Z_PROV_DASH_ATTRIBPROV"."ATTRIBUTED_PCP_NPI")
HAVING COUNT(1)>0