-- KE-12838
select sum(ITEM_COUNT) as ITEM_CNT
FROM TEST_KYLIN_FACT, TEST_ORDER, TEST_ACCOUNT as BUYER_ACCOUNT,
TEST_ACCOUNT as SELLER_ACCOUNT, EDW.TEST_CAL_DT as TEST_CAL_DT, TEST_CATEGORY_GROUPINGS,
EDW.TEST_SITES as TEST_SITES, EDW.TEST_SELLER_TYPE_DIM as TEST_SELLER_TYPE_DIM,
TEST_COUNTRY as BUYER_COUNTRY, TEST_COUNTRY as SELLER_COUNTRY
where TEST_KYLIN_FACT.ORDER_ID = TEST_ORDER.ORDER_ID
AND TEST_ORDER.BUYER_ID = BUYER_ACCOUNT.ACCOUNT_ID
AND TEST_KYLIN_FACT.SELLER_ID = SELLER_ACCOUNT.ACCOUNT_ID
AND TEST_KYLIN_FACT.CAL_DT = TEST_CAL_DT.CAL_DT
AND TEST_KYLIN_FACT.LEAF_CATEG_ID = TEST_CATEGORY_GROUPINGS.LEAF_CATEG_ID AND TEST_KYLIN_FACT.LSTG_SITE_ID = TEST_CATEGORY_GROUPINGS.SITE_ID
AND TEST_KYLIN_FACT.LSTG_SITE_ID = TEST_SITES.SITE_ID
AND TEST_KYLIN_FACT.SLR_SEGMENT_CD = TEST_SELLER_TYPE_DIM.SELLER_TYPE_CD
AND BUYER_ACCOUNT.ACCOUNT_COUNTRY = BUYER_COUNTRY.COUNTRY
AND SELLER_ACCOUNT.ACCOUNT_COUNTRY = SELLER_COUNTRY.COUNTRY