-- join with filter in left input
SELECT FACT1.CAL_DT, TEST_ACCOUNT.ACCOUNT_ID, SUM(FACT1.ITEM_COUNT)
FROM
(
  SELECT SELLER_ID, ITEM_COUNT, CAL_DT
  FROM TEST_KYLIN_FACT
  WHERE SELLER_ID > 10000037
) FACT1
LEFT JOIN TEST_ACCOUNT
ON FACT1.SELLER_ID = TEST_ACCOUNT.ACCOUNT_ID
GROUP BY FACT1.CAL_DT, TEST_ACCOUNT.ACCOUNT_ID