WITH A AS (
SELECT PRICE, ITEM_COUNT, SELLER_ID + 21 AS SELLER_ID
FROM TEST_KYLIN_FACT
),
B AS (
SELECT ACCOUNT_ID, ACCOUNT_COUNTRY
FROM TEST_ACCOUNT
)
SELECT SUM(PRICE), ACCOUNT_COUNTRY
FROM A INNER JOIN B
ON A.SELLER_ID = B.ACCOUNT_ID
GROUP BY ACCOUNT_COUNTRY