WITH A AS (
SELECT PRICE, ITEM_COUNT, SELLER_ID + 22 AS SELLER_ID
FROM TEST_KYLIN_FACT
),
B AS (
SELECT ACCOUNT_ID AS ACCOUNT_ID, ACCOUNT_COUNTRY AS ACCOUNT_COUNTRY
FROM
(
SELECT ACCOUNT_ID + 22 AS ACCOUNT_ID, ACCOUNT_COUNTRY AS ACCOUNT_COUNTRY, ACCOUNT_SELLER_LEVEL AS LEVEL
FROM TEST_ACCOUNT
)
)
SELECT SUM(PRICE), ACCOUNT_COUNTRY
FROM A LEFT JOIN B
ON A.SELLER_ID = B.ACCOUNT_ID
GROUP BY ACCOUNT_COUNTRY
