select a.LSTG_FORMAT_NAME,a.LEAF_CATEG_ID,c.SITE_ID
from (
select LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID,count(distinct SELLER_ID) as type_SELLER_ID
from TEST_KYLIN_FACT
where CAL_DT = '2012-01-01'
group by LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID
)a
inner join (
select LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID,count(distinct SELLER_ID) as type_SELLER_ID
from TEST_KYLIN_FACT
where CAL_DT = '2012-01-01'
group by LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID
)b
on a.LSTG_FORMAT_NAME=b.LSTG_FORMAT_NAME
and a.LEAF_CATEG_ID=b.LEAF_CATEG_ID
left join TEST_CATEGORY_GROUPINGS as c
on a.LSTG_SITE_ID=c.SITE_ID