select * from TEST_ACCOUNT
inner join (
select SELLER_ID from TEST_KYLIN_FACT where SELLER_ID > 0
) TEST_KYLIN_FACT on TEST_KYLIN_FACT.SELLER_ID=TEST_ACCOUNT.ACCOUNT_ID
right join TEST_COUNTRY
on TEST_ACCOUNT.ACCOUNT_COUNTRY = TEST_COUNTRY.COUNTRY
