SELECT  "LINEORDER"."LO_ORDERKEY" as "LO_ORDERKEY",
 "CUSTOMER"."C_CUSTKEY" as "C_CUSTKEY",
 "SUPPLIER"."S_SUPPKEY" as "S_SUPPKEY"
 FROM  "SSB"."LINEORDER" as "LINEORDER"
 INNER JOIN "SSB"."CUSTOMER" as "CUSTOMER"
 ON "LINEORDER"."LO_CUSTKEY"="CUSTOMER"."C_CUSTKEY"
 LEFT JOIN "SSB"."SUPPLIER" as "SUPPLIER"
 ON "LINEORDER"."LO_SUPPKEY"="SUPPLIER"."S_SUPPKEY"