SELECT nvl("LINEORDER"."LO_CUSTKEY", 123) as "CC3",
 "LINEORDER"."LO_ORDERKEY" as "LO_ORDERKEY",
 "LINEORDER"."LO_ORDERKEY" + 1 as "CC1",
 "LINEORDER"."LO_QUANTITY" + "CUSTOMER"."C_CUSTKEY" as "CC2",
 "LINEORDER"."LO_CUSTKEY" as "LO_CUSTKEY",
 "CUSTOMER"."C_MKTSEGMENT" as "C_MKTSEGMENT",
 "CUSTOMER"."C_CUSTKEY" as "C_CUSTKEY",
 "LINEORDER"."LO_SHIPMODE" as "LO_SHIPMODE",
 "LINEORDER"."LO_QUANTITY" as "LO_QUANTITY" FROM "SSB"."LINEORDER" as "LINEORDER" INNER JOIN "SSB"."CUSTOMER" as "CUSTOMER" ON "LINEORDER"."LO_CUSTKEY"="CUSTOMER"."C_CUSTKEY"