SELECT ID1, count(*), CAST(SUM(PRICE2) AS BIGINT), SUM(ID1), MAX(ID1), CAST(MAX(PRICE2) AS BIGINT), MIN(ID1), CAST(MIN(PRICE2) AS BIGINT),
COUNT(DISTINCT PRICE3)
FROM TEST_MEASURE
GROUP BY ID1 ORDER BY ID1