@startuml

package "Open Source Part" {

    ' server-base/controller
    component [server-base]

    component CommonService
    component DataSource
    component JobService
    component Modeling
    component Building
    component Query
    component Streaming

    DataSource --> CommonService
    Modeling --> DataSource
    Building --> Modeling
    Query --> Building
    JobService --> Building
    CommonService --> [core-metadata]

    [server-base] --> Query
    [server-base] --> JobService

    Streaming --> Building
}


package "Enterprise Part" {

    component Smart
    component Enterprise

    Smart --> Modeling
    Enterprise --> CommonService
}

@enduml
