-- KAP#16258
SELECT COUNT(DISTINCT IF(TEST_KYLIN_FACT1.PRICE>0,TEST_KYLIN_FACT1.LSTG_FORMAT_NAME,NULL))
FROM (
SELECT * FROM
TEST_KYLIN_FACT LEFT JOIN
TEST_ACCOUNT
ON SELLER_ID = ACCOUNT_ID
) TEST_KYLIN_FACT1