global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: 'xxx@qq.com'
  smtp_auth_username: 'xxx@qq.com'
  smtp_auth_password: 'xxx'
  smtp_require_tls: false
templates:
  - '/xxx/*.tmpl'    # alert template file path, please replace this with yourself
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: 'xxx@qq.com'           # receiver email address, please replace this with yourself
        html: '{{ template "email-kyligence.html" . }}'