SELECT {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__3224623892__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFMONTH("CALCS"."DATETIME0")}, SQL_VARCHAR)})}