SELECT {fn LTRIM({fn CONVERT({fn CONVERT({fn TRUNCATE("CALCS"."NUM4",0)}, SQL_BIGINT)}, SQL_VARCHAR)})} AS "TEMP_Test__2653491462__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn CONVERT({fn TRUNCATE("CALCS"."NUM4",0)}, SQL_BIGINT)}, SQL_VARCHAR)})}