SELECT {fn TIMESTAMPDIFF(SQL_TSI_SECOND,{fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)},"CALCS"."DATETIME0")} AS "TEMP_Test__1742439229__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPDIFF(SQL_TSI_SECOND,{fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)},"CALCS"."DATETIME0")}