SELECT (CASE "CALCS"."INT0" WHEN 1 THEN 'test1' WHEN 3 THEN 'test3' ELSE 'testelse' END) AS "TEMP_Test__3793551909__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE "CALCS"."INT0" WHEN 1 THEN 'test1' WHEN 3 THEN 'test3' ELSE 'testelse' END)