SELECT (CASE "CALCS"."STR0" WHEN 'TECHNOLOGY' THEN '*Anonymous*' ELSE "CALCS"."STR0" END) AS "TEMP_Test__3635999647__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE "CALCS"."STR0" WHEN 'TECHNOLOGY' THEN '*Anonymous*' ELSE "CALCS"."STR0" END)