SELECT {fn LTRIM({fn CONVERT({fn DAYOFYEAR("CALCS"."DATE2")}, SQL_VARCHAR)})} AS "TEMP_Test__1106997866__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFYEAR("CALCS"."DATE2")}, SQL_VARCHAR)})}