SELECT (CASE WHEN ("CALCS"."DATE2" < "CALCS"."DATE2") THEN 1 WHEN NOT ("CALCS"."DATE2" < "CALCS"."DATE2") THEN 0 ELSE NULL END) AS "TEMP_Test__3966211991__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."DATE2" < "CALCS"."DATE2") THEN 1 WHEN NOT ("CALCS"."DATE2" < "CALCS"."DATE2") THEN 0 ELSE NULL END)