SELECT {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATE2")}, SQL_VARCHAR)})} AS "TEMP_Test__178775464__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn MONTH("CALCS"."DATE2")}, SQL_VARCHAR)})}