SELECT (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM0" WHEN NOT ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM1" ELSE "CALCS"."NUM2" END) AS "TEMP_Test__372270648__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM0" WHEN NOT ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM1" ELSE "CALCS"."NUM2" END)