SELECT (CASE WHEN ("CALCS"."INT0" = 1) THEN 'yes' WHEN ("CALCS"."INT0" = 3) THEN 'yes3' ELSE 'no' END) AS "TEMP_Test__4172110977__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."INT0" = 1) THEN 'yes' WHEN ("CALCS"."INT0" = 3) THEN 'yes3' ELSE 'no' END)