SELECT {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn DAYOFWEEK("CALCS"."DATE2")} - 1)),{fn CONVERT("CALCS"."DATE2", SQL_DATE)})} AS "TEMP_Test__2996583857__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn DAYOFWEEK("CALCS"."DATE2")} - 1)),{fn CONVERT("CALCS"."DATE2", SQL_DATE)})}