SELECT {fn DAYOFMONTH({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})} AS "TEMP_Test__1635018952__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn DAYOFMONTH({fn CONVERT("CALCS"."DATETIME0", SQL_TIMESTAMP)})}