SELECT (CASE WHEN ("CALCS"."STR0" > "CALCS"."STR1") THEN "CALCS"."STR2" ELSE "CALCS"."STR3" END) AS "TEMP_Test__2270596010__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."STR0" > "CALCS"."STR1") THEN "CALCS"."STR2" ELSE "CALCS"."STR3" END)