-- KAP-8179
SELECT {fn FLOOR(((CASE WHEN ({fn MONTH({fn CURRENT_DATE()})} > {fn MONTH("Z_PROVDASH_UM_ED"."DOB")})
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
WHEN ({fn MONTH({fn CURRENT_DATE()})} < {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
WHEN (({fn MONTH({fn CURRENT_DATE()})} = {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
AND ({fn DAYOFMONTH({fn CURRENT_DATE()})} > {fn DAYOFMONTH("Z_PROVDASH_UM_ED"."DOB")})) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
ELSE ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
END) + 5) / 5)} AS "Age__5__bin_",   
{fn FLOOR((CASE WHEN ({fn MONTH({fn CURRENT_DATE()})} > {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
WHEN ({fn MONTH({fn CURRENT_DATE()})} < {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
WHEN (({fn MONTH({fn CURRENT_DATE()})} = {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
AND ({fn DAYOFMONTH({fn CURRENT_DATE()})} > {fn DAYOFMONTH("Z_PROVDASH_UM_ED"."DOB")})) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
ELSE ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) END) / 5)} AS "Age__bin_",   
AVG({fn CONVERT((CASE WHEN ({fn MONTH({fn CURRENT_DATE()})} > {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
WHEN ({fn MONTH({fn CURRENT_DATE()})} < {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
WHEN (({fn MONTH({fn CURRENT_DATE()})} = {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
AND ({fn DAYOFMONTH({fn CURRENT_DATE()})} > {fn DAYOFMONTH("Z_PROVDASH_UM_ED"."DOB")})) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
ELSE ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
END), SQL_DOUBLE)}) AS "avg_Calculation_61643039908483074_ok",   
COUNT(DISTINCT "Z_PROVDASH_UM_ED"."MEMBER_ID") AS "ctd_MEMBER_ID_ok" 
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED" 
WHERE ("Z_PROVDASH_UM_ED"."FULL_NAME" = 'JONATHAN AREND') 
GROUP BY {fn FLOOR((CASE WHEN ({fn MONTH({fn CURRENT_DATE()})} > {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
WHEN ({fn MONTH({fn CURRENT_DATE()})} < {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
WHEN (({fn MONTH({fn CURRENT_DATE()})} = {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
AND ({fn DAYOFMONTH({fn CURRENT_DATE()})} > {fn DAYOFMONTH("Z_PROVDASH_UM_ED"."DOB")})) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
ELSE ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) END) / 5)},   
{fn FLOOR(((CASE WHEN ({fn MONTH({fn CURRENT_DATE()})} > {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
WHEN ({fn MONTH({fn CURRENT_DATE()})} < {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
THEN ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) 
WHEN (({fn MONTH({fn CURRENT_DATE()})} = {fn MONTH("Z_PROVDASH_UM_ED"."DOB")}) 
AND ({fn DAYOFMONTH({fn CURRENT_DATE()})} > {fn DAYOFMONTH("Z_PROVDASH_UM_ED"."DOB")})) 
THEN {fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} 
ELSE ({fn TIMESTAMPDIFF(SQL_TSI_YEAR,"Z_PROVDASH_UM_ED"."DOB",{fn CURRENT_DATE()})} - 1) END) + 5) / 5)};