-- #6244
select LSTG_SITE_ID , ORDER_ID, SELLER_ID from (
  select LSTG_SITE_ID, ORDER_ID, SELLER_ID from TEST_KYLIN_FACT group by LSTG_SITE_ID, ORDER_ID, SELLER_ID
   union all
  select LSTG_SITE_ID, ORDER_ID, SELLER_ID from TEST_KYLIN_FACT group by LSTG_SITE_ID, ORDER_ID, SELLER_ID
  )
 group by LSTG_SITE_ID, ORDER_ID, SELLER_ID