global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds. Default is every 1 minute
  scrape_timeout: 10s  # Set the scrape timeout to every 10 seconds. Default is every 10 seconds
  evaluation_interval: 15s # Set the evaluation interval to every 15 seconds. Default is every 1 minute

scrape_configs:
  - job_name: Kyligence Enterprise  # should be equals to Application Name
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /kylin/api/prometheus  # endpoint for prometheus
    scheme: http