SELECT
  SUM(
    { fn CONVERT({ fn SIGN("KYLIN_SALES"."PRICE") }, SQL_BIGINT) }
  ) AS "sum_Calculation_4185251491172913201_ok",
  SUM({ fn CONVERT(1, SQL_BIGINT) }) AS "sum_Number_of_Records_ok"
FROM
  "DEFAULT"."TEST_KYLIN_FACT" "KYLIN_SALES"
  INNER JOIN "DEFAULT"."TEST_CATEGORY_GROUPINGS" "KYLIN_CATEGORY_GROUPINGS" ON (
    (
      "KYLIN_SALES"."LEAF_CATEG_ID" = "KYLIN_CATEGORY_GROUPINGS"."LEAF_CATEG_ID"
    )
    AND (
      "KYLIN_SALES"."LSTG_SITE_ID" = "KYLIN_CATEGORY_GROUPINGS"."SITE_ID"
    )
  )
  INNER JOIN "EDW"."TEST_CAL_DT" "KYLIN_CAL_DT" ON (
    "KYLIN_SALES"."CAL_DT" = "KYLIN_CAL_DT"."CAL_DT"
  )
  INNER JOIN "DEFAULT"."TEST_ACCOUNT" "SELLER_ACCOUNT" ON (
    "KYLIN_SALES"."SELLER_ID" = "SELLER_ACCOUNT"."ACCOUNT_ID"
  )
HAVING
  (COUNT(1) > 0)
