SELECT {fn LTRIM({fn CONVERT({fn QUARTER("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__1352954729__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn QUARTER("CALCS"."DATETIME0")}, SQL_VARCHAR)})}