SELECT {fn LTRIM({fn RTRIM({fn LTRIM({fn CONVERT("CALCS"."DATE2", SQL_VARCHAR)})})})} AS "TEMP_Test__3182504774__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn RTRIM({fn LTRIM({fn CONVERT("CALCS"."DATE2", SQL_VARCHAR)})})})}