SELECT {fn TIMESTAMPADD(SQL_TSI_HOUR,{fn HOUR("CALCS"."DATETIME0")},{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})} AS "TEMP_Test__2494207196__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_HOUR,{fn HOUR("CALCS"."DATETIME0")},{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})}