SELECT (CASE WHEN ("CALCS"."INT0" > 3) THEN 'yes' WHEN NOT ("CALCS"."INT0" > 3) THEN 'no' ELSE 'I dont know' END) AS "TEMP_Test__468880478__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."INT0" > 3) THEN 'yes' WHEN NOT ("CALCS"."INT0" > 3) THEN 'no' ELSE 'I dont know' END)