SELECT (CASE WHEN ({fn DAYOFMONTH({fn CURRENT_DATE()})} = {fn DAYOFMONTH({fn CURRENT_DATE()})}) THEN 1 WHEN NOT ({fn DAYOFMONTH({fn CURRENT_DATE()})} = {fn DAYOFMONTH({fn CURRENT_DATE()})}) THEN 0 ELSE NULL END) AS "TEMP_Test__3426973691__0_",
  1 AS "X__alias__0"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY 1