SELECT {fn TIMESTAMPADD(SQL_TSI_DAY,{fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("CALCS"."DATE2")} - 1)),0)}, SQL_BIGINT)},{fn CONVERT("CALCS"."DATE2", SQL_DATE)})} AS "TEMP_Test__3628113816__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn TIMESTAMPADD(SQL_TSI_DAY,{fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("CALCS"."DATE2")} - 1)),0)}, SQL_BIGINT)},{fn CONVERT("CALCS"."DATE2", SQL_DATE)})}