SELECT (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM0" ELSE "CALCS"."NUM1" END) AS "TEMP_Test__2784685147__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."NUM0" ELSE "CALCS"."NUM1" END)