SELECT (CASE WHEN ("CALCS"."STR1" = 'CLOCKS') THEN '*Anonymous*' WHEN ("CALCS"."STR1" = 'DVD') THEN '*Public*' ELSE "CALCS"."STR1" END) AS "TEMP_Test__801500456__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."STR1" = 'CLOCKS') THEN '*Anonymous*' WHEN ("CALCS"."STR1" = 'DVD') THEN '*Public*' ELSE "CALCS"."STR1" END)