SELECT (CASE WHEN ("CALCS"."NUM0" <> {fn ABS("CALCS"."NUM0")}) THEN 1 WHEN NOT ("CALCS"."NUM0" <> {fn ABS("CALCS"."NUM0")}) THEN 0 ELSE NULL END) AS "TEMP_Test__4117526434__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."NUM0" <> {fn ABS("CALCS"."NUM0")}) THEN 1 WHEN NOT ("CALCS"."NUM0" <> {fn ABS("CALCS"."NUM0")}) THEN 0 ELSE NULL END)