SELECT (CASE WHEN ("CALCS"."DATETIME0" > "CALCS"."DATETIME0") THEN 1 WHEN NOT ("CALCS"."DATETIME0" > "CALCS"."DATETIME0") THEN 0 ELSE NULL END) AS "TEMP_Test__3360301593__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."DATETIME0" > "CALCS"."DATETIME0") THEN 1 WHEN NOT ("CALCS"."DATETIME0" > "CALCS"."DATETIME0") THEN 0 ELSE NULL END)