SELECT {fn LTRIM({fn CONVERT({fn DAYOFYEAR("CALCS"."DATETIME0")}, SQL_VARCHAR)})} AS "TEMP_Test__1241275899__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn CONVERT({fn DAYOFYEAR("CALCS"."DATETIME0")}, SQL_VARCHAR)})}