SELECT {fn LTRIM({fn RTRIM({fn LTRIM({fn CONVERT("CALCS"."DATETIME0", SQL_VARCHAR)})})})} AS "TEMP_Test__1528725084__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn LTRIM({fn RTRIM({fn LTRIM({fn CONVERT("CALCS"."DATETIME0", SQL_VARCHAR)})})})}