SELECT (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."STR2" WHEN NOT ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."STR3" ELSE "CALCS"."STR0" END) AS "TEMP_Test__2192126901__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY (CASE WHEN ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."STR2" WHEN NOT ("CALCS"."NUM0" > "CALCS"."NUM1") THEN "CALCS"."STR3" ELSE "CALCS"."STR0" END)