SELECT {fn CONVERT({fn LTRIM({fn CONVERT("CALCS"."DATE2", SQL_VARCHAR)})}, SQL_DATE)} AS "TEMP_Test__3576106439__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn CONVERT({fn LTRIM({fn CONVERT("CALCS"."DATE2", SQL_VARCHAR)})}, SQL_DATE)}