--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT {fn CONVERT({fn TRUNCATE({fn TIMESTAMPDIFF(SQL_TSI_DAY,{fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK({fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)})} - 2), 7)})),{fn CONVERT({fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)}, SQL_DATE)})},{fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATETIME0")} - 2), 7)})),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})})} / 7,0)}, SQL_BIGINT)} AS "TEMP_Test__110287328__0_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY {fn CONVERT({fn TRUNCATE({fn TIMESTAMPDIFF(SQL_TSI_DAY,{fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK({fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)})} - 2), 7)})),{fn CONVERT({fn CONVERT("CALCS"."DATE2", SQL_TIMESTAMP)}, SQL_DATE)})},{fn TIMESTAMPADD(SQL_TSI_DAY,(-1 * ({fn MOD((7 + {fn DAYOFWEEK("CALCS"."DATETIME0")} - 2), 7)})),{fn CONVERT("CALCS"."DATETIME0", SQL_DATE)})})} / 7,0)}, SQL_BIGINT)}