SELECT CASE WHEN "CALCS"."INT2" = 0 THEN NULL ELSE ( "CALCS"."INT3" / "CALCS"."INT2" ) END AS "TEMP_Test__3653306930__1_"
FROM "TDVT"."CALCS" "CALCS"
GROUP BY CASE WHEN "CALCS"."INT2" = 0 THEN NULL ELSE ( "CALCS"."INT3" / "CALCS"."INT2" ) END