/*
 * Copyright (C) 2016 Kyligence Inc. All rights reserved.
 *
 * http://kyligence.io
 *
 * This software is the confidential and proprietary information of
 * Kyligence Inc. ("Confidential Information"). You shall not disclose
 * such Confidential Information and shall use it only in accordance
 * with the terms of the license agreement you entered into with
 * Kyligence Inc.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

KylinApp.constant('kapEnglishConfig', {
  kapService:{
    "statementHeader":"Service Statement",
    "serviceEndTime":"Service End Time",
    "evaluationStatement":"You are using evaluation version of KAP. If you need the most professional services and products base on Apache Kylin. Please contact us!",
    "statement":"You are using KAP enterprise product and service. If you have any issues about KAP, please contact us. We will continue to provide you with quality products and services from Apache Kylin core team.",
    "requestTip":"To request license, please contact with Kyligence sales support channel with the License Request file."
  },
  user:{
    setting: 'Settings',//reset password
    profile: 'Profile',
    changePassword: 'Change password',
    oldPassword: 'Old password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    tip_error_not_same: 'Password and confirm password are not the same.',
    tip_error_user_exits:'The user already exists',
    updatePassword: 'Update Password',
    tip_username_invalid: 'Username invalid.',
    tip_password_invalid: 'Password invalid.',
    success_resetSuccess: 'Reset password successfully.',
    failed_reset: 'Failed to reset password.',
    users: 'Users',
    submit: 'Submit',
    close: 'Close',
    addUser: 'Add User',
    password: 'Password',
    role: 'Role',
    analyst: 'Analyst',
    modeler: 'Modeler',
    admin: 'Admin',
    editUser: 'Edit User',
    user: 'User',
    usertheaditems: [
      {attr: 'username', name: 'Username'},
      {attr: 'admin', name: 'Admin'},
      {attr: 'modeler', name: 'Modeler'},
      {attr: 'analyst', name: 'Analyst'},
      {attr: 'disabled', name: 'Status'},
      {attr: 'action', name: 'Actions'}
    ],
    editRole: 'Edit Role',
    resetPassword: 'Reset Password',
    drop: 'Drop',
    enable: 'Enable',
    disable: 'Disable',
    alert_sure_to_drop: 'Are you sure to drop the user ?',
    success_drop: 'Drop user successfully',
    success_disable: 'Disable user successfully',
    success_enable: 'Enable user successfully',
    tip_failed_list_users: 'Failed to list users.',
    success_add_user: 'Add user successfully',
    success_update_user: 'Update user successfully'
  },
  login:{
    username: 'Username',
    password: 'Password',
    loginIssue: 'Login Issue?',
    loginIn: 'Log In',
    loginInNow: 'Login In...',
    error: 'Unable to login, please check your username/password.'
  },
  header:{
  chooseProject: 'Choose Project',
  login: 'Login',
  logout: 'Logout',
  help: 'Help',
  welcome: 'Welcome',
  documents: [
    {link:'http://kyligence.io',displayName:'About Us'},
    {link:'https://kyligence.gitbooks.io/kap-manual/content/en/',displayName:'KAP Manual'},
    {link:'https://kybot.io',displayName:'KyBot Service'}
  ],
  requestLicense:'Generate License Request File',
  selectLanguage: 'Languages'
  },
  /*
   module of  project
   */
  project:{
    /*
    part of manage project
     */
    info_no_result: 'No Result.',
    info_no_project: 'No Project.',
    info_load_project: 'Loading Projects...',
    theaditems: [
      {attr: 'name', name: 'Name'},
      {attr: 'owner', name: 'Owner'},
      {attr: 'description', name: 'Description'},
      {attr: 'create_time', name: 'Create Time'}
    ],
    action: 'Action',
    manageProject: 'Manage project',
    ac_project_edit: 'Edit',
    ac_project_delete: 'Delete',
    ac_project_backup: 'Backup',
    cubes: 'Cubes',   //project-cubes begin
    cubeName: 'Cube Name',
    cubeActions: 'Actions',
    ac_cube_detail: 'detail',
    access: 'Access',  //project-access begin
    ac_access_grant: 'Grant',
    ac_access_cancel: 'Cancel',
    tip_access: '<div style="text-align: left"><label>What does access mean to cube?</label><ul><li>CUBE QUERY: Access to query cube</li><li>CUBE OPERATION: Access to rebuild, resume and cancel jobs. Also include access of CUBE QUERY.</li><li>CUBE MANAGEMENT: Access to edit/delete cube. Also include access of CUBE OPERATION.</li><li>CUBE ADMIN: Full access to cube and jobs, including access management.</li></ul></div>',
    accessName: 'Name',
    plac_accessName: 'User NT Account...',
    accessType: 'Type',
    accessTypeUser: 'User',
    accessTypeRole: 'Role',
    accessAccess: 'Access',
    accessUpdate: 'Update',
    accessPermission: 'Permission',
    chooses_accessUpdate_deaf:'-- select access -- ',
    chooses_accessUpdate: {
                    READ: {name: 'CUBE QUERY', value: 'READ', mask: 1},
                    MANAGEMENT: {name: 'CUBE EDIT', value: 'MANAGEMENT', mask: 32},
                    OPERATION: {name: 'CUBE OPERATION', value: 'OPERATION', mask: 64},
                    ADMINISTRATION: {name: 'CUBE ADMIN', value: 'ADMINISTRATION', mask: 16}
                 },
    accessRevoke: 'Revoke',
    externalFilters: 'External Filters', //project-External Filters begin
    ac_externalFilters_filter: 'Filter',
    efNewFilter: 'New Filter',
    efFilterName: 'Filter Name',
    plac_efFilterName: 'You can use letters, numbers, and underscore characters ',
    checkInfo_require_efFilterName: 'The filter name is required',
    checkInfo_invalid_efFilterName: 'The filter name is invalid',
    efTableType: 'Table Name',
    efResourcePath: 'Resource Path',
    plac_efResourcePath: 'You can use letters, numbers, and underscore characters "_"',
    checkInfo_require_efResourcePath: 'The resource path is required',
    checkInfo_invalid_efResourcePath: 'The resource path is invalid',
    efDescription: 'Description',
    plac_efDescription: 'Filter Description..',
    ac_efClose: 'Close',
    ac_efSubmit: 'Submit',
    /*
    part of add project
     */
    addProject: 'Project',
    addAdd: 'Add Project',
    addTitle: 'New Project',
    addProjectName: 'Project Name',
    plac_addProjectName: 'You can use letters, numbers, and underscore characters "_"',
    checkInfo_require_addProjectName: 'The project name is required',
    checkInfo_invalid_addProjectName: 'The project name is invalid',
    addProjectDescription: 'Description',
    plac_addProjectDescription: 'Project Description..',
    addClose: 'Close',
    addSubmit: 'Submit',
    total:'Total',//sum of project
    projectConfig:'Project Config',
    property:'Property'
  },
  name:'kylin',
  /*
   module of model
   */
  model:{
    modelClone: 'MODEL CLONE',//cube clone
    targetProject: 'Target Project is',
    selectProject: 'select a project',
    newModelName: 'New Model Name:',
    submit: 'Submit',
    close: 'Close',
    /*
     management of model
     */
    Model: 'Model',
    Measure: 'Measure',
    paramValue: 'Param Value',
    model: 'Model',
    schema:['Model Info','Data Mode','Dimensions','Measures','Settings'],
    models: 'Models',
    theaditems : [
      {attr: 'name', name: 'Name'},
      {attr: 'project', name: 'Project'},
      {attr: 'owner', name: 'Owner'},
      {attr: 'fact_table', name: 'Fact Table'},
      {attr: 'last_modified', name: 'Last Modified Time'}
    ],
    actions: 'Actions',
    wizardSteps: [
      {title: 'Model Info', src: 'partials/modelDesigner/model_info.html', isComplete: false, form: 'model_info_form'},
      {title: 'Data Model', src: 'partials/modelDesigner/data_model.html', isComplete: false, form: 'data_model_form'},
      {
        title: 'Dimensions',
        src: 'partials/modelDesigner/model_dimensions.html',
        isComplete: false,
        form: 'model_dimensions_form'
      },
      {
        title: 'Measures',
        src: 'partials/modelDesigner/model_measures.html',
        isComplete: false,
        form: 'model_measure_form'
      },
      {
        title: 'Settings',
        src: 'partials/modelDesigner/conditions_settings.html',
        isComplete: false,
        form: 'model_setting_form'
      }
    ],
    info_no_model: 'No Model',
    info_create_model: 'Click here to create your model',
    next: 'Next',
    prev: 'Prev',
    save: 'Save',
    grid: 'grid',    //grid of model begin
    gridTheadItems:[
        {attr: 'name', name: 'Column Name'},
        {attr: 'datatype', name: 'Data Type'},
        {attr: 'cardinality', name: 'Cardinality'},
        {attr: 'comment', name: 'Comment'}
    ],
    gridModelDesign: 'Model Designer',
    gridModelInfo: 'Model Info',
    gridInUseTip:'Tip',
    gridColumnInUse_part_one: 'This column is in use in Cube',
    gridColumnInUse_part_two: '',
    gridTableInUse_part_one: 'This table is in use in Cube',
    gridTableInUse_part_two: '',
    gridMIModelName: 'Model Name',
    tip_title: 'gridMIModelName',
    tip_body_model_name: '<li>Model name is unique name of entire system.</li><li>Can not edit model name after created.</li>',
    check_info_required_model_name: 'Model name is required.',
    check_info_invalid_model_name: 'Model name is invalid.',
    gridMIDescription: 'Description',
    check_info_warning_MI: '<div class="box box-danger"><div class="box-header with-border"> <i class="fa fa-warning"></i><h3 class="box-title">Warning!</h3></div> <div class="box-body callout callout-warning"><ol><li>Project can\'t be empty</li><li>Model Name can\'t be empty</li></ol></div></div>',
    gridDataModel: 'Data Model',
    gridDMFactTable: 'Fact Table',
    gridDMLookupTables: 'Lookup Tables',
    gridDMNoLookupTables: 'No Lookup Tables',
    gridDMID: 'ID',
    gridDMAlias: 'Alias',
    gridDMTableType:'Table Type',
    gridDMTableName: 'Table Name',
    gridDMTableKind: 'Table Kind',
    gridDMJoinType: 'Join',
    gridDMJoinCondition: 'Join condition',
    gridDimensions: 'Dimensions',
    gridDSID: 'ID',
    gridDSTableName: 'Table Name',
    gridDSColumns: 'Columns',
    gridDSSelectAll: 'Select All',
    gridDSDataType:'Data Type',
    gridDSCardinality:'Cardinality',
    gridMeasure: 'Measure',
    gridMSID: 'ID',
    gridMSColumn: 'column',
    gridMSNoMetric : 'No Measures',
    gridMSSelectMeasure: 'Select your measures',
    gridMSFactTable: 'Fact Table',
    gridMSSelectAll: 'Select All',
    gridMSDataType:'Data Type',
    gridMSCardinality:'Cardinality',
    gridSettings: 'Settings',
    gridSTPartition: 'Partition',
    gridSTPartitionType: 'Partition Type',
    gridSTPartitionDate: 'Partition Date Column',
    tip_gridSTPartitionDate: '<li>Partition date column not required,leave as default if cube always need full build</Li><li>Column should contain date value (type can be Date, Timestamp, String, VARCHAR, Int, Integer, BigInt, etc.)</li>',
    gridSTPartitionDateSelect: '--Select Partition Column--',
    gridSTPartitionDateFormat: 'Date Format',
    gridSTPartitionDateFormatSelect: '--Select Date Format--',
    gridSTSetSeparate: 'Has a separate "time of the day" column ?',
    tip_tile_gridHasSepTimeColumn: 'Separate Time Column',
    tip_gridSTSetSeparate: 'For cases where fact table saves date and hour at two columns',
    gridHasParTimeColumn: 'Partition Time Column',
    tip_gridParTimeColumn: 'Column should contain time value (type can be Timestamp, String, VARCHAR, etc.)',
    gridHasSepTimeColumnSelect: '--Select Partition Column--',
    gridHasSepTimeColumnTF: 'Time Format',
    gridHasSepTimeColumnTFSelect: '--Select Time Format--',
    gridSTFilter: 'Filter',
    plac_gridSTFilter: 'The filter condition, no clause \'WHERE\' needed',
    //gridSTWhere: 'Where',
    edit: 'Edit',  //edit of model begin
    editDMSelectFact: '-- Select Fact Table --',
    editDMAddLookupTable: 'Add Join Table',
    editDMSelectLookup: '-- Select Join Table --',
    editDMActions: 'Actions',
    editDMLookupAdd: 'Add',
    editDMLookupAdd: 'Edit',//lookup table modal
    editDMLookupTableName: 'Join Table Name',
    editDMLookupNewJoin: ' New Join Condition',
    tip_join_delete: 'delete',
    tip_header_lookup_modal: ' <h4 class="box-title">Tips</h4>',
    tip_body_lookup_modal: '<ol class="text-info"><li>Pick up lookup table at first</li><li>Specify join relationship between fact table and chosen lookup table.</li><li>Join condition have to be same as will be used in query</li></ol>',
    ac_lookup_ok: 'OK',
    ac_lookup_cancel: 'Cancel',
    clone: 'Clone',
    drop: 'Drop',
    stats:'Stats',
    visualization: 'Visualization'
  },
  cube:{
    cubeClone: 'CUBE CLONE',//cube clone
    targetProject: 'Target Project is',
    selectProject: 'select a project',
    newCubeName: 'New Cube Name:',
    submit: 'Submit',
    close: 'Close',
    cubeName: 'Cube Name',
    tip_cube_required: 'Cube name is required.',
    tip_cube_name_invalid: 'Cube name is invalid.',
    tip_tableAlias_name_invalid:'Table alias is invalid(A Combination of numbers, uppercase letters or underscores)',
    cubeCubeDesigner: 'Cube Designer',
    cubeSave: 'Save',
    cubeNext: 'Next',
    cubePrev: 'Prev',
    cubesIn: '-- All --',
    ac_cube: 'Cube',
    aggregationGroups: 'Aggregation Groups',
    theaditems: [
      {attr: 'name', name: 'Name'},
      {attr: 'detail.model_name', name: 'Model'},
      {attr: 'status', name: 'Status'},
      {attr: 'size_kb', name: 'Cube Size'},
      {attr: 'input_records_count', name: 'Source Records'},
      {attr: 'last_build_time', name: 'Last Build Time'},
      {attr: 'owner', name: 'Owner'},
      {attr: 'create_time_utc', name: 'Create Time'}
    ],
    aggregationGroups: 'Aggregation Groups',
    actions: 'Actions',
    schema: ['Cube Info','Dimensions','Measures','Refresh Setting','Advanced Setting','Raw Table(Beta)','Configuration Overwrites','Overview'],
    admins: 'Admins',
    storage: 'Storage',
    streaming: 'Streaming',
    cubeActions:['Drop','Edit','Build','Refresh','Merge','Disable','Enable','Purge','Clone'],
    tip_drop_cube: 'Drop the cube, related jobs and data permanently.',
    tip_edit_cube: 'Edit the cube',
    tip_build_cube: 'Build the cube',
    tip_refresh_cube: 'Refresh the cube',
    tip_merge_cube: 'Merge the cube',
    tip_disable_cube: 'Disable the cube',
    tip_enable_cube: 'Enable the cube',
    tip_purge_cube: 'Purge the cube, all cube data will be purged',
    tip_clone_cube: 'Clone the cube under current project',
    edit: 'Edit',
    view: 'View',
    SegmentId: 'Segment ID',
    cubeItems: ['Grid','SQL','JSON(Cube)','Access','Notification','Storage'],
    cubeNoNotification: 'Notification List(Common Separated)',
    ac_cubeNotification_save: 'Save',
    cubeHBHTable: 'HTable:',
    cubeHBRegionCount: 'Region Count:',
    cubeHBSize: 'Size:',
    cubeHBStartTime: 'Start Time:',
    cubeHBEndTime: 'End Time:',
    cubeHBTotalSize:  'Total Size:',
    cubeHBTotalNumber: 'Total Number:',
    cubeHBNoHBaseInfo: 'No HBase Info.',

    segmentName:'Segment Name:',
    segmentPath:'Segment Path:',
    fileCount:'File Number:',
    storageSize:'Storage Size:',
    dateRangeStart:'Range Start Time:',
    dateRangeEnd:'Range End Time:',
    NoStorageInfo: 'No Storage Info.',

    rawTableSegmentPath:'Raw Table Segment Path:',
    rawTableFileCount:'Raw Table File Number:',
    rawTableStorageSize:'Raw Table StorageSize:',

    cubeCIModelName: 'Model Name',
    cubeCIAddChooseModel: '-- Choose Model --',
    tip_title_cube_name: 'Cube Name',
    tip_body_cube_name: '<li>Cube name is unique name of entire system.</li><li>Can not edit cube name after created.</li>',
    cubeCINotifiEmail: 'Notification Email List',
    cubeCINotifiEvents: 'Notification Events',
    tip_body_cubeCINotifiEvents: 'These statuses will trigger an email notification.',
    cubeCIDescription: 'Description',
    cubeDSAddDS: 'Add Dimension',
    cubeDSNormal: 'Normal',
    cubeDSDerived: 'Derived',
    cubeDSSwitchDer: 'derived',
    cubeDSColumn: 'Column',
    cubeDSDatatype : 'Datatype',
    cubeDSCardinality:'Cardinality',
    cubeDSComment : 'Comment',
    cubeDSSwitchNormal: 'normal',
    cubeDSAddDimensions: 'Add Dimensions',
    cubeDSID: 'ID',
    cubeDSName: 'Name',
    tip_cubeDSName: 'Name..',
    tip_cubeDSDiName: 'dimension name..',
    cubeDSTableName: 'Table Name',
    tip_select_table: 'Select a table',
    tip_select_lookup: 'Select a lookup table',
    cubeDSType: 'Type',
    cubeDSActions: 'Actions',
    info_no_following_columns: 'There are following columns defined in multiple dimensions. <small>This is not recommended!</small>',
    info_no_cube: 'No Cube',
    cubeDSEditDSEdit: 'Edit Dimension',
    cubeDSEditDSAdd: 'Add Dimension',//add dimension begin
    tip_no_dimension_name: 'The Dimension Name is required.',
    tip_derived_dimension: 'Derived dimension only comes from lookup table.',
    cubeDSColumnName: 'Column Name',
    cubeDSSelectColumn: '-- Select Column --',
    ac_delete_cubeDSColumn: 'Delete',
    cubeDSNewHierarchy: 'New Hierarchy',
    tip_cubeDSNewHierarchy: 'Drag level into the order you prefer.',
    cubeDSNewDerived: 'New Derived',
    tip_title_cubeDS: 'Tips',
    tip_body_cubeDS: ' <li>Type in any input box for auto suggestion</li><li>Pick up Fact Table from Star Schema Tables first</li><li>Data Type should match with Hive Table\'s Data Type</li><li>Join Type have to be same as will be used in query</li><li>Using Derived for One-One relationship between columns, like ID and Name</li>',
    ac_ok_cube: 'OK',
    ac_cancel_cube: 'Cancel',
    cubeDSAutoGenerate_part_one: 'Auto Generate Dimensions',//Auto Generate Dimensions begin
    cubeDSAutoGenerate_part_two: 'This is a helper for you to batch generate dimensions.', cubeDSColumns: 'Columns',
    cubeDSColumns: 'Columns',
    cubeDSFactTable: '[Fact Table]',
    cubeDSLookupTable: '[Lookup Table]',
    cubeDSSelectAll:'Select All',
    tip_about_derived_column:'for more about derived column.',
    tip_title_DSAutoGenerate: 'Auto Generate Rules',
    tip_body_DSAutoGenerate: '<li>In fact table: one normal dimension will be auto generated per column.</li><li>In lookup table: you can choose to generate a normal dimension or a derived dimension.</li>',
    cubeMSName: 'Name',//measures begin
    cubeMSExpression: 'Expression',
    cubeMSParameters: 'Parameters',
    cubeMSParamType: 'Param Type',
    cubeMSParamValue: 'Param Value',
    tip_cubeMSParamValue: '<li>Only accept single column in param value with "Column" type</li><li>Distinct Count is approximate, please indicate Error Rate, higher accuracy degree accompanied with larger storage size and longer build time</li>',
    cubeMSParamValueSelect: '-- Select a Column --',
    cubeMSConstant: 'constant',
    cubeMSReturnType: 'Return Type',
    cubeMSActions: 'Actions',
    cubeMSEditMS: 'Edit Measure',
    cubeMSMeasureName: 'measure name..',
    cubeMSDatatype:'Data Type',
    cubeMSCardinality:'Cardinality',
    cubeMSComment:'Comment',
    tip_cubeMSExpression: 'All cubes have to contain one measure for Count(1), suggest use "_Count_" as name (Has been generated automatically)',
    tip_extendedType: 'Kylin won’t save more than this number of bytes for each extended column. If exceeded it will be truncated.',
    tip_topn: 'Will use this column for SUM and Order by. For constant value 1, will use SUM(1).',
    tip_hostcolumn: 'Host column is the dimension to derive from, e.g. page_id',
    tip_extendedcolumn: 'Extended column is derived from host, e.g. page_url. No filters on extended column!',
    cubeMSOK: 'OK',
    cubeMSCancel: 'Cancel',
    cubeMSParameterAdd: 'Add Parameter',
    cubeMSParameterSelect: 'Select Group By Column',
    cubeMSID: 'ID',
    cubeMSColumn: 'Column',
    cubeMSEncoding: 'Encoding',
    cubeMSLength: 'Length',
    cubeMSNewColumn:'New Column',
    cubeRSAutoMerge: 'Auto Merge Thresholds',//refresh_settings begin
    tip_cubeRSAutoMerge: 'The thresholds will be checked ascendingly to see if any consectuive segments\' time range has exceeded it. For example the [7 days, 30 days] will result in daily incremental segments being merged every 7 days, and the 7-days segments will get merged every 30 days.',
    cubeRSNewThresholds: 'New Thresholds',
    cubeRSRetentionThreshold: 'Retention Threshold',
    tip_cubeRSRetentionThreshold: 'By default it\'s \'0\',which will keep all historic cube segments ,or will keep latest [Retention Threshold] days cube segments.',
    cubeRSPartitionStart: 'Partition Start Date',
    tip_cubePartitionDate: 'Please input start date when partition date column is defined in model.',
    cubeASID: 'ID',//Advanced Setting begin
    cubeASAggregationGroups: 'Aggregation Groups',
    cubeASIncludes: 'Includes',
    cubeASMandatoryDimensions: 'Mandatory Dimensions',
    plac_cubeAS: 'Select Column...',
    cubeASHierarchyDimensions: 'Hierarchy Dimensions',
    cubeASNewHierarchy: 'New Hierarchy',
    cubeASJointDimensions: 'Joint Dimensions',
    cubeASNewJoint: 'New Joint',
    cubeASNewAggregationGroup: 'New Aggregation Group',
    cubeASRowkeys: 'Rowkeys',
    tip_encoding:'true',
    tip_encoding_dict:'Use dictionary to encode dimension values. dict encoding is very compact but vulnerable for ultra high cardinality dimensions.',
    tip_encoding_fixed_length:'Use a fixed-length("length" parameter) byte array to encode integer dimension values, with potention value truncations.',
    tip_encoding_int:'Deprecated, use latest integer encoding intead.',
    tip_encoding_integer_v1:'Deprecated, use latest integer encoding instead.',
    tip_encoding_integer_v2:'Use N bytes to encode integer values, where N equals the length parameter and ranges from 1 to 8. [-2^(8*N-1),2^(8*N-1)) is supported for integer encoding with length of N.',
    tip_encoding_fixed_length_hex:'Use a fixed-length("length" parameter) byte array to encode the hex string dimension values, like 1A2BFF or FF00FF, with potention value truncations. Assign one length parameter for every two hex codes.',
    tip_encoding_date:'Use 3 bytes to encode date dimension values.',
    tip_encoding_time:'Use 4 bytes to encode timestamps, supporting from 1970-01-01 00:00:00 to 2038/01/19 03:14:07. Millisecond is ignored.',
    tip_encoding_bool:'Use 1 byte to enode, valid value include：true, false, TRUE, FALSE, True, False, t, f, T, F, yes, no, YES, NO, Yes, No, y, n, Y, N, 1, 0',
    tip_length:'true',
    tip_length_fixed_length_part_one:'The first ',
    tip_length_fixed_length_part_two:'bytes of the selected field are encoded values.',
    tip_length_fixed_length_hex_part_one:'Support ',
    tip_length_fixed_length_hex_part_two:'characters',
    tip_length_integer_v2:'Support range is',
    noConfigRawTableInfo:'No Raw Table Configuration Information',
    unSupportRawTable:'Only KAP PLUS Provides Raw Table',
    needConfigRawTable:'Config Raw Table',
    cubeOfRawTable: 'Raw Table',
    rawtableASColumn:'Column',
    rawtableASTableName:'Table Name',
    rawtableASEncoding:'Encoding',
    rawtableASIndex:'Index',
    rawtableMustSetSorted:'You must set one column with an index value of sorted!',
    rawtableMustSetSortedWidthDateEncoding:'Only columns with the date or time encoding are allowed to set with an index value of sorted',
    rawtableMustSetSingleSorted:'Only one column is allowed to set with an index value of sorted!',
    tip_title_cubeASRowkeys: {name:'Rowkey',watch:true},
    tip_body_cubeASRowkeys: '<h4>Shard By this column?</h4><p>If specified as "true", cube data will be sharded according to its value.</p><h4>RowKey Encoding</h4><ol><li>"dict" Use dictionary to encode dimension values. dict encoding is very compact but vulnerable for ultra high cardinality dimensions.</li><li>"integer" Use N bytes to encode integer values, where N equals the length parameter and ranges from 1 to 8. [-2^(8*N-1),2^(8*N-1)) is supported for integer encoding with length of N.</li><li>"int" Deprecated, use latest integer encoding instead.</li><li>"date" Use 3 bytes to encode date dimension values. </li><li>"time" Use 4 bytes to encode timestamps, supporting from 1970-01-01 00:00:00 to 2038/01/19 03:14:07. Millisecond is ignored. </li><li>"fix_length" Use a fixed-length("length" parameter) byte array to encode integer dimension values, with potential value truncations. </li><li>"fixed_length_hex" Use a fixed-length("length" parameter) byte array to encode the hex string dimension values, like 1A2BFF or FF00FF, with potential value truncations. Assign one length parameter for every two hex codes.</li></ol>',
    tip_body_cubeRawTable: '<h4>Shard By this column?</h4><p>If specified as "true", cube data will be sharded according to its value.</p><h4>RowKey Encoding</h4><ol><li>"dict" encoding will try to build a dictionary for the dimension</li><li>"fixed_length" encoding will encode the dimension vlaues by fixed length bytes with padding</li><li>"int" encoding uses variable integer to encode integers </li></ol>',
    cubeASID: 'ID',
    cubeASColumn: 'Column',
    cubeASEncoding: 'Encoding',
    cubeASLength: 'Length',
    cubeASShardBy: 'Shard By',
    cubeASDatatype:'Data Type',
    cubeASCardinality:'Cardinality',
    tip_rowkey_column_name: 'rowkey column name..',
    tip_rowkey_column_length: 'rowkey column length..',
    tip_false_by_default: 'false by default',
    tip_Column_Name: 'Column Name..',
    cubeASNewRowkeyColumn: 'New Rowkey Column',
    plac_cubeCOKey: 'Key',//Configuration Overwrites begin
    tip_cubeCOKey: 'Property name is required.',
    plac_cubeCOValue: 'Value',
    tip_cubeCOValue: 'Property value is required.',
    cubeCOProperty: 'Property',
    cubeCOTips: 'Tips',
    tip_cubeCOTips: 'Cube level properties will overwrite configuration in kylin.prperties',
    cubeOVModelName: 'Model Name',//Overview begin
    cubeOVCubeName: 'Cube Name',
    cubeOVFactTable: 'Fact Table',
    cubeOVLookupTable: 'Lookup Table',
    cubeOVDimensions: 'Dimensions',
    cubeOVMeasures: 'Measures',
    cubeOVDescription: 'Description',
    tip_loading_cubes: 'Loading Cubes...',
    cubeASBuilderClass:'Builder Class',
    cubeASReuse:'Reuse',
    cubeASActions: 'Actions',
    cubeASAdvancedDictionaries:'Advanced Dictionaries',
    cubeASEditDictionaries:'Edit Dictionaries',
    cubeASSelectColumn: '-- Select a Column --',
    selectBuildClass: '-- Select a Builder Class -- ',
    tip_dictionaries:'Special settings for dictionaries. Leave blank by default.',
    cubeASDictionaries:'Dictionaries',
    cubeASOK: 'OK',
    cubeASCancel: 'Cancel',
    kaTopic: {name:'Topic',watch:true}, //kafka begin
    tip_Kafka_topic: 'Kafka topic is required.',
    tip_kafka_topic_invalid: 'Kafka topic is invalid.',
    kaCluster: 'Cluster',
    tip_input_kafkaConfig_topic: 'Input kafkaConfig topic',
    kaHost: 'Host',
    kaPort: 'Port',
    kaActions: 'Actions',
    tip_input_broker: 'Input broker ID',
    tip_input_broker_host: 'Input broker host',
    tip_input_broker_port: 'Input broker port',
    kaBroker: 'Broker',
    kaSave: 'Save',
    kaCancel: 'Cancel',
    kaKafkaSetting: 'Kafka Setting',
    kaAdvancedSetting: 'Advanced Setting',
    kaTimeout: 'Timeout',
    tip_input_kafkaConfig_timeout: 'Input kafkaConfig timeout',
    tip_timeout_invalid: 'Kafka timeout is invalid.',
    tip_timeout_required: 'Kafka timeout is required.',
    kaBufferSize: 'Buffer Size',
    tip_kafkaConfig_bufferSize: 'Input kafkaConfig bufferSize',
    tip_bufferSize_invalid: 'Kafka bufferSize is invalid.',
    tip_bufferSize_required: 'Kafka bufferSize is required.',
    kaMargin: 'Margin',
    tip_input_kafkaConfig_margin: 'Input kafkaConfig margin',
    tip_kafka_margin_invalid: 'Kafka margin is invalid.',
    tip_kafka_margin_required: 'Kafka margin is required.',
    kaParserSetting: 'Parser Setting',
    kaParserName: 'Parser Name',
    tip_input_kafkaConfig_parserName: 'Input kafkaConfig parserName',
    tip_kafka_parser_name_invalid: 'Kafka parser name is invalid.',
    tip_kafka_parser_name_required: 'Kafka parser name is required.',
    kaParserTimestampField: 'Parser Timestamp Field',
    kaSelectColumn: 'select a column',
    kaParserProperties: 'Parser Properties',
    tip_parser_properties_invalid: 'Parser properties is invalid.',
    tip_parser_properties_required: 'Parser properties is required.',
    tip_body_kafka_topic: 'Input the kafka topic that contains source data.',
    tip_body_timeout:'Set timeout for kafka client.',
    tip_body_buffer_size:'Set byte size for kafka client’s buffer.',
    tip_body_margin:'When the messages in kafka is not strictly sorted on timestamp, read more data (expressed in ts) before and after the specified interval to avoid data loss.',
    tip_body_parser_name:'Set the parser to parse source data messages. The default parser works for json messages with a timestamp field.',
    tip_body_parser_timestamp_field:'Provide the name of the timestamp field to the default parser.',
    tip_body_parser_properties:'Provide a list of KV properties to the parser, delimited by semicolon.',
    backup_cube:'Backup Cube',
    includeDimension:'Include Dimensions'
  },
  monitor:{
    monitor: 'Monitor',
    jobs: 'Jobs',
    slowQueries: 'Slow Queries',
    jobsCubeName: 'Cube Name:',
    plac_jobsCubeName: 'Filter ...',
    jobsJobsIn: 'Jobs in',
    jobConfig:{},// refer to jobConfig.js
    tip_no_job: 'No Job.',
    tip_loading_jobs: 'Loading Jobs ...',
    jobResume: 'Resume',
    jobDiscard: 'Discard',
    jobPause:'Pause',
    jobDiagnosis: 'Diagnosis',
    tip_jobDiagnosis: 'Download Diagnosis Info For This Job',
    tip_jobResume: 'Resume the Job',
    tip_jobPause: 'Pause the Job',
    tip_jobDiscard: 'Discard the Job',
    jobsDetailInfo: 'Detail Information',//job detail begin
    tip_jobsDetailInfo: 'Collapse',
    jobsJobName: 'Job Name',
    jobsJobID: 'ID',
    jobsStatus: 'Status',
    jobsDuration: 'Duration',
    jobsMapReduceWaiting: 'MapReduce Waiting',
    jobsStart: 'Start',
    jobsStepName: 'Step Name:',
    jobsDataSize: 'Data Size:',
    tip_Parameters: 'Parameters',
    tip_Log: 'Log',
    tip_MRJob: 'MRJob',
    jobsEnd: 'End',
    tip_no_job_selected: 'No Job Selected.',
    jobsModalParameters: 'Parameters',
    jobsModalOutput: 'Output',
    jobsModalLoading: 'loading ...',
    jobsModalCmdOutput: 'cmd_output',
    jobsModalClose: 'Close',
    jobsModalSubmit: 'Submit',
    jobsCubeMergeConfirm: 'CUBE MERGE CONFIRM',//jobs merge modal begin
    jobsNOSegment: 'NO SEGMENT TO MERGE.',
    jobsPartitionDate: 'PARTITION DATE COLUMN',
    jobsMergeStart: 'MERGE START SEGMENT',
    jobsMergeEnd: 'MERGE END SEGMENT',
    jobsSegmentDetail: 'START SEGMENT DETAIL',
    jobsStartDate: 'Start Date (Include)',
    jobsEndDate: 'End Date (Exclude)',
    jobsLastbuildTime: 'Last build Time',
    jobsLastbuildID: 'Last build ID',
    jobsEndSegment: 'END SEGMENT DETAIL',
    tip_cube_segment: 'There exists a build request of this cube, the job may be running or error. If you need a new build, please wait for its complete or discard it.',
    tip_no_partition: 'No partition date column defined.',
    jobsCubeRefreshConfirm: 'CUBE REFRESH CONFIRM',//jobs refresh modal begin
    jobsNoSegmentRefresh: 'No Segment to refresh.',
    jobsPartitionDateColumn: 'PARTITION DATE COLUMN',
    jobsRefreshSegment: 'REFRESH SEGMENT',
    jobsSegmentDetail: 'EGMENT DETAIL',
    jobsCubeBuildConfirm: 'CUBE BUILD CONFIRM',//jobs submit modal begin
    tip_no_project_selected: 'No project selected',//job slow query begin
    tip_no_slow_query: 'No Slow Query.',
    tip_loading_queries: 'Loading Queries ...',
  },
  insight:{
    insight: 'Insight',
    tables: 'Tables',//query.html begin
    tip_no_table: 'No Table.',
    tip_loading_Tables: 'Loading Tables...',
    newQuery: 'New Query',
    savedQueries: 'Saved Queries',
    queryHistory: 'Query History',
    tip_list_tables: 'Tips: Ctrl+Shift+Space or Alt+Space(Windows), Command+Option+Space(Mac) to list tables/columns in query box.',
    project: 'Project:',
    limit: 'LIMIT',
    ac_submit: 'Submit',
    sqlName: 'SQL Name:',
    description: 'Description',
    ac_resubmit: 'Resubmit',
    ac_remove: 'Remove',
    tip_no_query_history: 'No Query History.',
    queriedAt: 'Queried At: ',
    inProject: 'in Project:',
    status: ' Status:',
    tip_no_query_result: 'No Query Result.',
    tip_no_saved_query: 'No Saved Query.',
    startTime: 'Start Time:',//query detail begin
    duration: 'Duration: ',
    ac_return: 'Rerun',
    ac_save: 'Save',
    queryString: 'Query String',
    queryStatus: ['Failed','Success','Executing...'],
    cubes: 'Cubes',
    results: 'Results',
    tip_curQuery_result_partial: '!Note: Current results are partial, please click \'Show All\' button to get all results.',
    showAll: 'Show All',
    visualization: 'Visualization',
    grid: 'Grid',
    ac_export: 'Export',
    tip_loading: 'Loading...',
    tip_more: 'More',
    graphType: 'Graph Type',
    dimensions: 'Dimensions',
    chooseDimension: '-- choose dimension --',
    metrics: 'Metrics',
    plac_select_metrics: 'Select Metrics..',
    chooseMetrics: '-- choose metrics --',
    tip_no_graph_generated: 'No Graph Generated.',
    saveQuery: 'Save Query', //Save Query Modal begin
    project: 'Project',
    name: 'Name',
    plac_name: 'Name..',
    plac_description: 'Description..',
    ac_close: 'Close'
  },
  data_source:{
    edit: 'Edit',
    data_source: 'Data Source',
    extendInformation: 'Extend Information',
    tables: 'Tables',//--table tree begin
    tip_load_hive_table: 'Load Hive Table',
    tip_load_table_tree: 'Load Hive Table From Tree',
    unload_table: 'Unload Table',
    reload_table:'Reload Table',
    tip_add_streaming_table: 'Add Streaming Table',
    titleAddHiveTable: 'Load Hive Table Metadata',//modal addHiveTable begin
    project: 'Project:',
    tableNames: 'Table Names:(Separate with comma)',
    plac_table_with_comma: 'table1,table2  By default,system will choose \'Default\' as database,you can specify database like this \'database.table\'',
    sync: 'Sync',
    unsync: 'Unsync',
    cancel: 'Cancel',
    titleAddHiveTableFromTree: 'Load Hive Table Metadata From Tree',//modal addHiveTableFromTree begin
    plac_filter: 'Filter ...',
    tip_loading_databases: 'Loading Databases...',
    tip_loading_tables: 'Loading Tables...',
    ac_show_more: 'Show More',
    ac_show_all: 'Show All',
    titleRemoveHiveTable: 'UnLoad Hive Table Metadata',//modal removeHiveTable begin
    titleAddStreamingSource: 'Streaming Table And Cluster Info',//modal addStreamingSource begin
    prev: 'Prev',
    next: 'Next',
    submit: 'Submit',
    //part of modal addStreamingSource-- loadStreamingTable  --step 1
    info_loadStreamingTable: 'Need to input streaming source record here, will detect the source schema and create a table schema for streaming.',
    tip_streaming_sourceSchema: 'input Streaming source record to generate schema.',
    tip_table_schemaChecked: 'Source json invalid, Please correct your schema and generate again.',
    tip_table_schemaChecked_detail: '<li>Choose \'timestamp\' type column for streaming table.</li><li>By default, system will choose \'Default\' as database, you can specify database like this \'database.table\'</li><li>derived time dimensions are calculated from timestamp field to help analysis against different time granularities.</li>',
    tableName: 'Table Name',
    tip_table_name: 'Table name is required.',
    column: 'Column',
    columnType: 'Column Type',
    comment: 'Comment',
    plac_select_column_type: 'select a column type',
    timestamp: 'timestamp',
    derivedTimeDimension: 'derived time dimension',
    tip_choose_timestamp: 'You should choose at least one \'timestamp\' type column generated from source schema.',
    tableSchema: 'Table Schema:',//--table detail begin
    columns: 'Columns',
    extendInforFDFmation: 'Extend Information',
    streamingCluster: 'Streaming Cluster',
    name: 'TABLE NAME',
    hiveDatabase: 'Hive DATABASE',
    tableType: 'TABLE TYPE',
    snapshotTime: 'SNAPSHOT TIME',
    location: 'LOCATION',
    inputFormat: 'INPUT FORMAT',
    outputFormat: 'OUTPUT FORMAT',
    owner: 'OWNER',
    totalFileNumber: 'TOTAL FILE NUMBER',
    totalFileSize: 'TOTAL FILE SIZE',
    partitioned: 'PARTITIONED',
    partitionColumns: 'PARTITION COLUMNS',
    plac_column: 'Filter ...',
    theaditems: [
      {attr: 'id', name: 'ID'},
      {attr: 'name', name: 'Column Name'},
      {attr: 'datatype', name: 'Data Type'},
      {attr: 'cardinality', name: 'Cardinality'},
      {attr: 'comment', name: 'Comment'}
    ],
    tip_no_table_selected: 'No Table Selected.',
    noTables: 'No tables',
    tip_load_hive_table: 'Click here to load your hive table',
    tip_no_project_selected: 'No project selected',
    tip_select_project: 'Please select your project first',
    tip_select_table: 'Select your table',
    sampleData:'Sample Data',
    columnName:'Column',
    cardinality:'Cardinality',
    noSampleData:'No Sample Data',
    collectStatistics:'Collect Statistics',
    statistics:'Statistics',
    metaData:'Meta Data',
    lastModifiedTime:'Last Modified Time',
    totalRows:'Total Rows',
    maxLengthValue:'Max Length Value',
    maxValue:'Max Value',
    minLengthValue:'Min Length Value',
    minValue:'Min Value',
    nullCount:'Null Count',
    noCluster:'No Cluster',
    loadingCluster:'Loading Cluster Info',
    useLessTopic:'The Topic is temporarily unavailable！',
    clusterFormError:'Make sure you are not repeat or empty the broker info！',
    collectKafkaSampleData:'Collect Streaming Sample Data'
  },
  system:{
    system: 'System',
    serverConfig: 'Server Config ',
    serverEnvironment: 'Server Environment ',
    actions: 'Actions',
    reloadMetadata: 'Reload Metadata',
    tip_reloadMetadata: 'Reload all metadata and clean cache',
    cleanUpStorage: 'Clean Up Storage',
    tip_cleanUpStorage: 'Clean unused HDFS and HBASE space',
    disableCache: 'Disable Cache',
    enableCache: 'Enable Cache',
    tip_enableCache: 'Enable Query Cache',
    setConfig: 'Set Config',
    tip_setConfig: 'Update Server Config',
    diagnosis: 'Diagnosis',

    diagnosisIntroduce:'provides KAP online diagnosis, optimization and service by the analysis of KAP generated diagnostic package',
    diagnosisTimeDis:'The time range of the generated diagnostic packet is three days before the generation time',
    diagnosisUploadBtn:'Key generation diagnostic package to KYBOT',
    diagnosisDownloadBtn:'Download diagnostic package',
    diagnosisUploadByHand:'Manual upload',
    diagnosisForPoorNetwork:'If there is no public network access, can choose manual upload, operation steps are as follows：',
    diagnosisForPoorNetworkActionSeq:['1.Download diagnostic package','2.Login KYBOT','3.Click the upload button on the top left corner of the home page and upload the selected diagnostic package on the upload page'],
    diagnosisFactoryPackage:'Generate diagnostic package',

    tip_diagnosis: 'Download Diagnosis Info For Current Project',
    backup:'Backup',
    tip_backup:'Global Backup',
    links: 'Links',
    updateConfig: 'Update Config',//modal updateConfig begin
    key: 'Key',
    tip_key: 'Config Key..',
    tip_required_key: 'Key is required.',
    value: 'Value',
    tip_value: 'Config Value..',
    tip_required_value: 'Value is required.',
    cancel: 'Cancel',
    update: 'Update'
  },
  alert:{
    error_info: 'Failed to take action.',
    success_grant: 'Access granted', //alert of AccessCtrl
    userNotFound: 'User not found!!',
    tip_sure_to_revoke: 'Are you sure to revoke the access?',
    success_access_been_revoked: 'The access has been revoked.',
    tip_to_reload_metadata: 'Are you sure to reload metadata and clean cache?',//alert of AdminCtrl
    success_server_environment: 'Server environment get successfully',
    success_server_config: 'Server config get successfully',
    success_cache_reload: 'Cache reload successfully',
    tip_clean_HDFS_HBase: 'Are you sure to clean up unused HDFS and HBase space?',
    success_storage_cleaned: 'Storage cleaned successfully!',
    success_cache_disabled: 'Cache disabled successfully!',
    tip_enable_query_cache: 'Are you sure to enable query cache?',
    success_cache_enabled: 'Cache enabled successfully',
    success_cardinality_job: 'Cardinality job was calculated successfully. . Click Refresh button ...',
    success_config_updated: 'Config updated successfully!',
    tip_no_project_selected: 'No project selected.',
    tip_to_disable_cache: 'Are you sure to disable query cache?',
    error_failed_to_load_query: 'Failed to load query.',//alert of BadQueryCtrl;
    success_notify_list_updated: 'Notify List updated successfully!',//alert of CubeCtrl
    tip_select_project: 'Please select your project first.',//alert of CubeEditCtrl
    tip_invalid_cube: 'Invalid cube json format..',
    tip_to_save_cube: 'Are you sure to save the cube ?',
    success_updated_cube: 'Updated the cube successfully',
    success_created_cube: 'Created the cube successfully.',
    tip_column_required: '[TOP_N] Group by Column is required',//alert of CubeMeasuresCtrl
    warning_column_required:'[TOP_N] ORDER|SUM by Column  is required',
    tip_remove_lookup_table: 'Once it\'s removed, all relative dimensions will be removed. Are you sure to remove the lookup table?',//alert of CubeModelCtrl
    tip_no_cube_detail: 'No cube detail info loaded.',//alert of cubesCtrl
    tip_no_cube_detail_loaded: 'No cube detail info loaded.',
    tip_sure_to_enable_cube: 'Are you sure to enable the cube? Please note: if cube schema is changed in the disabled period, all segments of the cube will be discarded due to data and schema mismatch.',
    success_Enable_submitted: 'Enable job was submitted successfully',
    tip_to_purge_cube: 'Are you sure to purge the cube?',
    success_purge_job: 'Purge job was submitted successfully',
    tip_disable_cube: 'Are you sure to disable the cube? ',
    success_disable_job_submit: 'Disable job was submitted successfully',
    tip_metadata_cleaned_up: 'Once it\'s dropped, your cube\’s metadata and data will be cleaned up and can\’t be restored back. ',
    tip_cube_drop: 'Cube drop is done successfully',
    tip_to_start_build: 'Are you sure to start the build ?',
    success_rebuild_job: 'Rebuild job was submitted successfully',
    tip_select_target_project: 'Please select target project.',
    tip_to_clone_cube: 'Are you sure to clone the cube? ',
    tip_for_clone_project: 'Cross project clone is not allowed now,  cube will be cloned into current project.',
    success_clone_cube: 'Clone cube successfully',
    success_rebuild_job: 'Rebuild job was submitted successfully',
    tip_rebuild_part_one: 'Empty cube segment found',
    tip_rebuild_part_two: ', do you want to merge segments forcely ?',
    //error_info: 'Failed to load external filters.',//alert of ExtFilterCtrl
    tip_to_delete_filter: 'Are you sure to delete ?',
    tip_delete_filter_part_one: 'Filter [',
    tip_delete_filter_part_two: '] has been deleted successfully!',
    tip_update_filter_part_two: '] updated successfully!',
    tip_create_filter_part_one: 'New Filter [',
    tip_create_filter_part_two: '] created successfully!',
    tip_to_resume_job: 'Are you sure to resume the job?',//alert of JobCtrl
    success_job_been_resumed: 'Job has been resumed successfully!',
    tip_to_discard_job: 'Are you sure to discard the job?',
    success_Job_been_discarded: 'Job has been discarded successfully!',
    success_Job_been_paused:'Job has been paused successfully!',
    tip_no_job_selected: 'No job selected.',
    error_failed_to_load_job: 'Failed to load job info, please check system log for details.',
    tip_invalid_model_json: 'Invalid model json format..',//alert of ModelEditCtrl
    tip_to_update_model: 'Are you sure to update the model?',
    tip_to_save_model: 'Are you sure to save the Model',
    tip_Please_note: 'Please note: if model schema is changed, all cubes of the model will be affected.',
    success_updated_model: 'Updated the model successfully.',
    success_created_model: 'Created the model successfully.',
    tip_to_drop_model: 'Are you sure to drop this model?',//alert of ModelCtrl
    success_model_drop_done: 'Model drop is done successfully',
    tip_select_target_project: 'Please select target project.',
    tip_to_clone_model: 'Are you sure to clone the model? ',
    success_clone_model: 'Clone model successfully',
    success_project_update: 'Project update successfully!',//alert of PageCtrl
    tip_new_project_created: 'New project created successfully!',
    tip_sure_to_delete: 'Are you sure to delete ?', //alert of ProjectContrl
    tip_sure_to_backup: 'Are you sure to backup ?',
    tip_project_delete_part_one: 'Project [',
    tip_project_delete_part_two: '] has been deleted successfully!',
    tip_project_backup_part_one: 'Project [',
    tip_project_backup_part_two: '] has been backed-up successfully!',
    success_new_query_saved: 'New query saved..',
    tip_to_leave_page: 'You\'ve executing query in current page, are you sure to leave this page?',
    tip_select_project: 'Please select a project.',//alert of SourceMetaCtrl
    tip_to_synchronize: 'Please input table(s) you want to synchronize.',
    tip_choose_project: 'Please choose your project first!.',
    tip_result_unload_title: 'Failed',
    tip_result_unload_body: 'Failed to synchronize following table(s): ',
    success_table_been_synchronized: 'The following table(s) have been successfully synchronized: ',
    tip_partial_loaded_title: 'Partial loaded!',
    tip_partial_loaded_body_part_one: 'The following table(s) have been successfully synchronized: ',
    tip_partial_loaded_body_part_two: '\n\n Failed to synchronize following table(s):',
    tip_save_streaming_table: 'Are you sure to save the streaming table and cluster info ?',
    success_updated_streaming: 'Updated the streaming successfully.',
    tip_created_streaming: 'Created the streaming successfully.',
    tip_to_remove_cluster: 'Are you sure to remove this cluster ?',
    getNoMessages:'Failed to load Streaming Sample Data!',
    streamingSaveMsg:'Get Sample Data successfully！',
    loadTableWidthCollectConfirm:'Do you want to automatically run the statistics job at the same time',
    unloadTableTip:'Are you sure to unload this table?',
    streamingSaveMsgError:'Failed to Get  Sample Data！',
    tip_model_be_used:'This model is still used by ',
    tip_model_be_used_by:'',
    warning_dictionaries_part_one:'The column named [',
    warning_dictionaries_part_two: '] already exists',
    oops:'Oops...',
    success:'Success!',
    warning_model_part_one:'The model named [',
    warning_model_part_two: '] already exists!',
    success_filecreat_part_one:'New Filter [',
    success_filecreat_part_two:'] created successfully!',
    warning_cube_part_one:'The cube named [',
    warning_cube_part_two: '] already exists!',
    check_cube_dimension:'Dimension can\'t be null',
    check_cube_measure_define:"Please define your metrics.",
    check_cube_measure_metric:"[COUNT] metric is required.",
    check_cube_aggregation_groups:"Each aggregation group can't be empty.",
    check_cube_rowkeys_int:"integer encoding column length should between 1 and 8.",
    check_cube_rowkeys_shard:"At most one 'shard by' column is allowed.",
    check_model_dimension:"No dimensions defined.",
    check_model_measure_define:"Please define your metrics.",
    check_look_up_primary_key:"Primary Key can't be null.",
    check_look_up_foreign_key:"Foreign Key can't be null.",
    error_cube_edit_query_param:"Failed to take action.",
    error_cube_edit_cube_detail:"No cube detail info loaded.",
    check_cube_dimensions_derived:"Please define your derived columns.",
    check_cube_dimensiona_value:"Derived value can't be null.",
    check_cube_dimensions_duplicate:"Duplicate column ",
    success_access:"Access granted!",
    check_look_up_column:" Column Type incompatible ",
    warning_measures_part_one:'The column named [',
    warning_measures_part_two: '] already exists!',
    duplicate_measures_part_one:'The measure named [',
    duplicate_measures_part_two: '] already exists!',
    warning_dimensions_name:"The name is required.",
    success_back:"Backup success!",
    tip_cubadd_cache:"Detect that you have not saved the cube edit information, whether to continue to edit?",
    tip_store_callback:'Backup Success！Path：',
    rawTableSaveError:'Failed to save the raw table setting!',
    collectStaticsSuccess:'Collect job start running!You can go to Monitor page to watch the progress!',
    hasCollectJob: 'There has been a running collect job!You can go to Monitor page to watch the progress!',
  },
  license:{
    aboutkap:"About KAP",
    version:"Version",
    dates:"Valid Period",
    statement:"License Statement",
    commit:"KAP Commit",
    kylincommit:"Kylin Commit"
  },
  snowModel:{
    delSnowModelTableTips:'Are you sure to delete this table？Please confirm that the table is not associated with other tables before deleting!',
    tableHasLink:'The table has no deleted associations and cannot be deleted！',
    limitLinkItself:'Do not allow to connect itself!',
    limitSetRootFact:'The table has a foreign key relationship,can not set RootFact!',
    linkDiffTypeTip:'Column type is not consistent！',
    rootFactCannotLinkOtherTable:'Root fact table can not connect to the other tables!',
    rootFactTableNeedNotSetAlias:'Root fact table can not set alias!',
    sameAliasWarn:'Alias cannot be repeated',
    cancel:'cancel',
    ok:'ok',
    save:'save',
    remove:'delete',
    delTable:'Delete Table',
    rootFactTable:'Root Fact Table',
    factTable:'Fact Table',
    loopUpTable:'Lookup Table',
    dimension:'Dimension',
    measure:'Measure',
    disable:'Disable',
    zoomIn:'ZoomIn',
    zoomOut:'ZoomOut',
    modelName:'Model Name:',
    modelDescription:'Model Description:',
    modelFilter:'Filter:',
    dateFormat:'Partition Date Format',
    timeFormat:'Partition Time Format',
    format:'Format:',
    joinTypeSet:'Join Type Setting',
    joinType:'Join Type:',
    jsonDesc:'Model JSON format data preview',
    modelSaveInfo:'Save model  information',
    modelFilterPlaceHolder:'The filter condition, no clause \'WHERE\' needed',
    errorRepeat:'A model already exists using this name！',
    hasCacheTip:'Monitor your last incomplete modeling data, load continue edit?',
    noDimension:'Dimension column is not set in the model',
    formatError:'Model data is not complete',
    noRootFact:'You are not set root fact table'
  }
});
