SELECT "Z_360_HEAT"."GAP_NAME" AS "GAP_NAME",
"Z_360_HEAT"."HCC_NAME" AS "HCC_NAME",
"Z_360_HEAT"."MEMBER_ID" AS "MEMBER_ID",
"Z_360_HEAT"."MEMBER_NAME" AS "MEMBER_NAME",
"Z_360_HEAT"."MRN" AS "MRN",
"Z_360_HEAT"."PAYER_LOB" AS "PAYER_LOB",
AVG("Z_360_HEAT"."HCC_RAF_SCORE") AS "avg_HCC_RAF_SCORE_ok",
AVG("Z_360_HEAT"."INCREMENTAL_RAF") AS "avg_INCREMENTAL_RAF_ok",
AVG("Z_360_HEAT"."TOTAL_RAF_SCORE") AS "avg_TOTAL_RAF_SCORE_ok",
((({fn YEAR("Z_360_HEAT"."MEMBER_DOB")} * 10000)
+ ({fn MONTH("Z_360_HEAT"."MEMBER_DOB")} * 100))
+ {fn DAYOFMONTH("Z_360_HEAT"."MEMBER_DOB")}) AS "md_MEMBER_DOB_ok"
FROM "POPHEALTH_ANALYTICS"."Z_360_HEAT" "Z_360_HEAT"
WHERE (('Patients by HCC Opportunity' = 'Patients by HCC Opportunity')
AND ("Z_360_HEAT"."PCP_NAME" = 'JONATHAN AREND')
AND ("Z_360_HEAT"."PCP_NAME" = 'JONATHAN AREND')
AND ("Z_360_HEAT"."GAP_TYPE" = 'HCC SUSPECT'))
GROUP BY "Z_360_HEAT"."GAP_NAME",   "Z_360_HEAT"."HCC_NAME",   "Z_360_HEAT"."MEMBER_ID",   "Z_360_HEAT"."MEMBER_NAME",   "Z_360_HEAT"."MRN",   "Z_360_HEAT"."PAYER_LOB",   ((({fn YEAR("Z_360_HEAT"."MEMBER_DOB")} * 10000) + ({fn MONTH("Z_360_HEAT"."MEMBER_DOB")} * 100)) + {fn DAYOFMONTH("Z_360_HEAT"."MEMBER_DOB")});