-- KAP-9000
SELECT (CASE WHEN ("Z_PROVDASH_UM_ED"."VASCULAR_DISEASE" = 1)
THEN 'Yes' ELSE 'No ' END) AS "Hx_of_Diabetes__copy_"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_UM_ED" "Z_PROVDASH_UM_ED"
GROUP BY (CASE WHEN ("Z_PROVDASH_UM_ED"."VASCULAR_DISEASE" = 1)
THEN 'Yes' ELSE 'No ' END)
ORDER BY 1 ASC;