SELECT "Z_PROVDASH_QPM_SCORE"."MEASURE_CODE" AS "MEASURE_CODE",
"Z_PROVDASH_QPM_SCORE"."MEASURE_DESC" AS "MEASURE_DESC",
AVG("Z_PROVDASH_QPM_SCORE"."BENCHMARK_RATE") AS "avg_BENCHMARK_RATE_ok",
AVG(("Z_PROVDASH_QPM_SCORE"."NPI_RATE" - "Z_PROVDASH_QPM_SCORE"."BENCHMARK_RATE")) AS "avg_Calculation_404761059420499972_ok",
AVG("Z_PROVDASH_QPM_SCORE"."NPI_RATE") AS "avg_NPI_RATE_ok"
FROM "POPHEALTH_ANALYTICS"."Z_PROVDASH_QPM_SCORE" "Z_PROVDASH_QPM_SCORE"
WHERE ("Z_PROVDASH_QPM_SCORE"."MEASURE_CODE" IN ('PQRS1', 'PQRS111', 'PQRS119', 'PQRS134', 'PQRS226'))
GROUP BY "Z_PROVDASH_QPM_SCORE"."MEASURE_CODE", "Z_PROVDASH_QPM_SCORE"."MEASURE_DESC"