@startmindmap
* Kylin Core Engine

** 0-元数据和系统管理
*** 01-元数据定义
**** RootPersistentEntity
*** 02-元数据一致性(以及同步机制)
**** AuditLog & Broadcast
**** Epoch
*** 03-元数据存储层
**** ResourceStore
*** 04-多级设置(KylinConfig)

** 1-数据源
*** 11-加载表元数据
*** 12-卸载表元数据
*** 13-重新加载表元数据
*** 14-表统计信息采样

** 2-模型管理
*** 21-基本元素
**** 定义维度
**** 定义度量
**** 定义可计算列
**** 定义表关联关系
*** 22-模型元数据导入导出

*** 23-索引管理
**** 索引类型
***** 聚合索引
***** 明细索引
**** 索引生成策略
***** 基于静态规则
**** 索引推荐优化策略
***** 基于查询历史

*** 24-Segment 管理
**** 基本特性
***** 构建
***** 刷新、删除
**** Segment 分区
***** Segment 一级日期分区
***** Segment 二级分区
**** Segment 索引关联
***** Segment 异构索引

*** 25-表快照管理
**** 构建/刷新快照
**** 缓慢变化维 Type2
**** 维度表分区构建

*** 26-Schema Change
**** 模型元数据变更
**** 表元数据变更
***** 表重载
***** 表卸载

** 3-构建引擎
*** 31-聚合索引构建
*** 32-明细索引构建
*** 33-表采样作业

** 4-查询引擎
*** 41-QueryACL
*** 42-查询路由逻辑-Route
*** 43-查询计划翻译-CalciteToSpark

** 5-作业调度引擎

** 6-系统维护工具和系统监控
*** 61-元数据备份恢复
*** 62-元数据升级
*** 63-元数据垃圾清理
*** 64-存储数据垃圾清理
*** 65-Kylin 服务指标监控
*** 66-Kylin 服务指标监控


@endmindmap
