SELECT "SN"."N_NAME", SUM(l_extendedprice) "REVENUE"
FROM TPCH."LINEITEM"
INNER JOIN TPCH."ORDERS" ON "L_ORDERKEY" = "O_ORDERKEY"
INNER JOIN TPCH."CUSTOMER" ON "O_CUSTKEY" = "C_CUSTKEY"
INNER JOIN TPCH."NATION" "CN" ON "C_NATIONKEY" = "CN"."N_NATIONKEY"
INNER JOIN TPCH."SUPPLIER" ON "L_SUPPKEY" = "S_SUPPKEY"
INNER JOIN TPCH."NATION" "SN" ON "S_NATIONKEY" = "SN"."N_NATIONKEY"
INNER JOIN TPCH."REGION" ON "SN"."N_REGIONKEY" = "R_REGIONKEY"
WHERE "R_NAME" = 'A' AND "CN"."N_NAME" = "SN"."N_NAME" AND "O_ORDERDATE" >= '2010-01-01' AND "O_ORDERDATE" < '2010-01-02'
GROUP BY "SN"."N_NAME"
ORDER BY "REVENUE" DESC