{
 "title": "KE Application Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ke_db_connections, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ke_db_connections{job=\"$job\"}, instance)"
    }
   },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project)" } }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Succeed",
   "type": "gauge",
   "description": "查询成功率",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\"})/sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\"})*100",
     "legendFormat": "succeed%"
    }
   ]
  },
  {
   "title": "Hit Index",
   "type": "gauge",
   "description": "查询命中索引率",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\",hit_index=\"true\"}) /sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_index%"
    }
   ]
  },
  {
   "title": "Hit Exactly Index",
   "type": "gauge",
   "description": "查询精确命中索引率",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\",hit_exactly_index=\"true\"}) / sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_exactly_index%"
    }
   ]
  },
  {
   "title": "Hit Cache",
   "type": "gauge",
   "description": "查询命中缓存率",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\",cache=\"true\"}) / sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_cache%"
    }
   ]
  },
  {
   "title": "Query/Build Analyse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Query Cost Distribution",
   "type": "piechart",
   "description": "查询耗时分布情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"3.0\"}[$__range]))",
     "legendFormat": "0-3s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"15.0\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"3.0\"}[$__range]))",
     "legendFormat": "3-15s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"60.0\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"15.0\"}[$__range]))",
     "legendFormat": "15-60s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"+Inf\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"60.0\"}[$__range]))",
     "legendFormat": "60+s"
    }
   ]
  },
  {
   "title": "Query Analyse",
   "type": "bargauge",
   "description": "查询分析(query_totals:查询总次数 query_fails:查询失败次数 hit_indexs:命中索引数 hit_caches:命中缓存次数)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\"}[$__range]))",
     "legendFormat": "query_totals"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"false\"}[$__range]))",
     "legendFormat": "query_fails"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",push_down=\"true\"}[$__range]))",
     "legendFormat": "push_downs"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",hit_index=\"true\"}[$__range]))",
     "legendFormat": "hit_indexs"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",cache=\"true\"}[$__range]))",
     "legendFormat": "hit_caches"
    },
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=\"$project\",hit_snapshot=\"true\"})",
     "legendFormat": "hit_snapshots"
    }
   ]
  },
  {
   "title": "Build Cost Distribution",
   "type": "piechart",
   "description": "构建耗时分布情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\",le=\"30.0\"}[$__range]))",
     "legendFormat": "0-30m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"60.0\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"30.0\"}[$__range]))",
     "legendFormat": "30-60m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"300.0\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"60.0\"}[$__range]))",
     "legendFormat": "60-300m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"+Inf\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\", le=\"300.0\"}[$__range]))",
     "legendFormat": "300+m"
    }
   ]
  },
  {
   "title": "Build Analyse",
   "type": "bargauge",
   "description": "构建分析(build_totals:构建总次数, build_fails:构建失败次数 build_total_minutes:构建总耗时 build_type_xxx_totals:对应类型的构建次数)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=\"$project\"}[$__range]))",
     "legendFormat": "build_totals"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"false\"}[$__range]))",
     "legendFormat": "build_fails"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_sum{job=\"$job\",instance=\"$instance\",project=\"$project\",succeed=\"true\"}[$__range]))",
     "legendFormat": "build_total_minutes"
    },
    {
     "expr": "sum by (job_type) (increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=\"$project\"}[$__range]))",
     "legendFormat": "build_type_{{job_type}}_totals"
    }
   ]
  },
  {
   "title": "Spark Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  },
  {
   "title": "Spark Tasks",
   "type": "gauge",
   "description": "spark任务(running_tasks:运行中的任务数 spark_tasks_utilization:spark资源利用率)",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"running\"}",
     "legendFormat": "running_tasks"
    },
    {
     "expr": "spark_tasks_utilization{job=\"$job\",instance=\"$instance\"} * 100",
     "legendFormat": "spark_tasks_utilization%"
    }
   ]
  },
  {
   "title": "Spark Tasks",
   "type": "timeseries",
   "description": "spark任务分析",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"running\"}",
     "legendFormat": "running_tasks"
    },
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"pending\"}",
     "legendFormat": "pending_tasks"
    }
   ]
  },
  {
   "title": "Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "TOP10 Model AVG Query Scan MB",
   "type": "bargauge",
   "description": "查询扫描字节数top10的模型",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,ke_queries_scan_bytes_sum{job=\"$job\",instance=\"$instance\",project=\"$project\"}/ke_queries_scan_bytes_count{job=\"$job\",instance=\"$instance\",project=\"$project\"}/1048576)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Query Scan MB 80%",
   "type": "timeseries",
   "description": "查询扫描字节百分位80%",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 38 },
   "targets": [
    {
     "expr": "ke_queries_scan_bytes{job=\"$job\",instance=\"$instance\",project=\"$project\",quantile=\"0.8\"}/1048576",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Query Scan MB 90%",
   "type": "timeseries",
   "description": "查询扫描字节百分位90%",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 46 },
   "targets": [
    {
     "expr": "ke_queries_scan_bytes{job=\"$job\",instance=\"$instance\",project=\"$project\",quantile=\"0.9\"}/1048576",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "TOP10 Model AVG Build Minutes",
   "type": "bargauge",
   "description": "模型构建耗时top10的模型",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (model) (ke_model_build_minutes_sum{job=\"$job\",project=\"$project\",succeed=\"true\"}) / sum by (model) (ke_model_build_minutes_count{job=\"$job\",project=\"$project\",succeed=\"true\"}))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Metadata Connections",
   "type": "graph",
   "description": "元数据库连接数",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ke_db_connections{instance=\"$instance\",state=\"active\"}",
     "legendFormat": "active"
    },
    {
     "expr": "ke_db_connections{instance=\"$instance\",state=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "http_error_count(/api/models/.+/segments)",
   "type": "graph",
   "description": "模型构建Http接口失败次数统计",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=~\"/api/models/.+/segments\",method=\"POST\",status=~\"4..\"}[5m]))",
     "legendFormat": "http_status=4.."
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=~\"/api/models/.+/segments\",method=\"POST\",status=~\"5..\"}[5m]))",
     "legendFormat": "http_status=5.."
    }
   ]
  },
  { "title": "HTTP Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Total number of requests",
   "type": "graph",
   "description": "http接口总请求频率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$job\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "graph",
   "description": "http接口总耗时分析",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "graph",
   "description": "http请求最大耗时情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "graph",
   "description": "http接口平均耗时情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\", instance=\"$instance\"}[4m]) / rate(http_server_requests_seconds_count{job=\"$job\", instance=\"$instance\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}