{
 "title": "KE Application Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ke_db_connections, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ke_db_connections{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(ke_job_counts{job=\"$job\",instance=\"$instance\"} ,project)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Succeed",
   "type": "gauge",
   "description": "查询成功率",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"})/sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"})*100",
     "legendFormat": "succeed%"
    }
   ]
  },
  {
   "title": "Hit Index",
   "type": "gauge",
   "description": "查询命中索引率",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\",hit_index=\"true\"}) /sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_index%"
    }
   ]
  },
  {
   "title": "Hit Exactly Index",
   "type": "gauge",
   "description": "查询精确命中索引率",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\",hit_exactly_index=\"true\"}) / sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_exactly_index%"
    }
   ]
  },
  {
   "title": "Hit Cache",
   "type": "gauge",
   "description": "查询命中缓存率",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\",cache=\"true\"}) / sum(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}) * 100",
     "legendFormat": "hit_cache%"
    }
   ]
  },
  { "title": "Query Analyse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Query Cost Distribution",
   "type": "piechart",
   "description": "查询耗时分布情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"3.0\"}[$__range]))",
     "legendFormat": "0-3s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"15.0\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"3.0\"}[$__range]))",
     "legendFormat": "3-15s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"60.0\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"15.0\"}[$__range]))",
     "legendFormat": "15-60s"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"+Inf\"}[$__range])) - sum(increase(ke_queries_seconds_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"60.0\"}[$__range]))",
     "legendFormat": "60+s"
    }
   ]
  },
  {
   "title": "Query Analyse",
   "type": "bargauge",
   "description": "查询分析(query_totals:查询总次数 query_fails:查询失败次数 hit_indexs:命中索引数 hit_caches:命中缓存次数)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range]))",
     "legendFormat": "query_totals"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"false\"}[$__range]))",
     "legendFormat": "query_fails"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",push_down=\"true\"}[$__range]))",
     "legendFormat": "push_downs"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_index=\"true\"}[$__range]))",
     "legendFormat": "hit_indexs"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",cache=\"true\"}[$__range]))",
     "legendFormat": "hit_caches"
    },
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_snapshot=\"true\"}[$__range]))",
     "legendFormat": "hit_snapshots"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "query rate in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}[1m]))",
     "legendFormat": "succeed"
    },
    {
     "expr": "sum(rate(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"false\"}[1m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Query Avg Duration",
   "type": "timeseries",
   "description": "query avg duration in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[1m])) / sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[1m]))",
     "legendFormat": "avg_duration"
    }
   ]
  },
  {
   "title": "Tiered Storage Query Amount",
   "type": "stat",
   "description": "击中分层存储的查询数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[$__range]))",
     "legendFormat": "query_amount%"
    }
   ]
  },
  {
   "title": "Tiered Storage Query Ratio",
   "type": "gauge",
   "description": "击中分层存储的查询比例",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[$__range])) / sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range]))*100",
     "legendFormat": "query_ratio%"
    }
   ]
  },
  {
   "title": "Tiered Storage Query Average Response Time",
   "type": "stat",
   "description": "击中分层存储的查询的平均响应时间",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[$__range])) / sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[$__range]))",
     "legendFormat": "query_average_response_time%"
    }
   ]
  },
  {
   "title": "Trend of Tiered Storage Query Amount",
   "type": "timeseries",
   "description": "近段时间内击中分层存储的查询数趋势",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[1m]))",
     "legendFormat": "query_amount"
    }
   ]
  },
  {
   "title": "Trend of Tiered Storage Query Ratio",
   "type": "timeseries",
   "description": "近段时间内击中分层存储的查询比例趋势 ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[1m])) / sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[1m]))*100",
     "legendFormat": "query_ratio%"
    }
   ]
  },
  {
   "title": "Trend of Tiered Storage Query Average Response Time",
   "type": "timeseries",
   "description": "近段时间内击中分层存储的查询平均响应时间趋势",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(ke_queries_seconds_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[1m])) / sum(increase(ke_queries_seconds_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",hit_second_storage=\"true\"}[1m]))",
     "legendFormat": "query_average_response_time"
    }
   ]
  },
  {
   "title": "Build Analyse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  },
  {
   "title": "Build Cost Distribution",
   "type": "piechart",
   "description": "构建耗时分布情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\",le=\"30.0\"}[$__range]))",
     "legendFormat": "0-30m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"60.0\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"30.0\"}[$__range]))",
     "legendFormat": "30-60m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"300.0\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"60.0\"}[$__range]))",
     "legendFormat": "60-300m"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"+Inf\"}[$__range])) - sum(increase(ke_model_build_minutes_bucket{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\", le=\"300.0\"}[$__range]))",
     "legendFormat": "300+m"
    }
   ]
  },
  {
   "title": "Build Analyse",
   "type": "bargauge",
   "description": "构建分析(build_totals:构建总次数, build_fails:构建失败次数 build_total_minutes:构建总耗时 build_type_xxx_totals:对应类型的构建次数)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range]))",
     "legendFormat": "build_totals"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"false\"}[$__range]))",
     "legendFormat": "build_fails"
    },
    {
     "expr": "sum(increase(ke_model_build_minutes_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}[$__range]))",
     "legendFormat": "build_total_minutes"
    },
    {
     "expr": "sum by (job_type) (increase(ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range]))",
     "legendFormat": "build_type_{{job_type}}_totals"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "System Storage Size",
   "type": "timeseries",
   "description": "System storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ke_storage_bytes{job=\"$job\",instance=\"$instance\",project=~\"$project\"}) by(project)",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "sum(ke_storage_bytes{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Garage Storage Size",
   "type": "timeseries",
   "description": "System Garage Storage ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ke_garbage_bytes{job=\"$job\",instance=\"$instance\",project=~\"$project\"}) by(project)",
     "legendFormat": "{{project}}"
    },
    {
     "expr": "sum(ke_garbage_bytes{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "all"
    }
   ]
  },
  { "title": "Spark Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Sparder Health",
   "type": "timeseries",
   "description": "Sparder Health Status, 1 means healthy,  0 means unhealthy",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ke_sparder_up{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "sparder_up"
    }
   ]
  },
  {
   "title": "Spark Task Utilization",
   "type": "timeseries",
   "description": "Spark Utilization, number of running tasks / spark \nexecutor total cores",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spark_tasks_utilization{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "spark_tasks_utilization"
    }
   ]
  },
  {
   "title": "Spark Tasks",
   "type": "gauge",
   "description": "spark任务(running_tasks:运行中的任务数 spark_tasks_utilization:spark资源利用率)",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"running\"}",
     "legendFormat": "running_tasks"
    },
    {
     "expr": "spark_tasks_utilization{job=\"$job\",instance=\"$instance\"} * 100",
     "legendFormat": "spark_tasks_utilization%"
    }
   ]
  },
  {
   "title": "Spark Tasks",
   "type": "timeseries",
   "description": "number of spark running tasks and number of spark pending tasks",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"running\"}",
     "legendFormat": "running_tasks"
    },
    {
     "expr": "spark_tasks{job=\"$job\",instance=\"$instance\",state=\"pending\"}",
     "legendFormat": "pending_tasks"
    }
   ]
  },
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "TOP10 Model AVG Query Scan MB",
   "type": "bargauge",
   "description": "查询扫描字节数top10的模型",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,ke_queries_scan_bytes_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\"}/ke_queries_scan_bytes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}/1048576)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Query Scan MB 80%",
   "type": "timeseries",
   "description": "查询扫描字节百分位80%",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 81 },
   "targets": [
    {
     "expr": "ke_queries_scan_bytes{job=\"$job\",instance=\"$instance\",project=~\"$project\",quantile=\"0.8\"}/1048576",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Query Scan MB 90%",
   "type": "timeseries",
   "description": "查询扫描字节百分位90%",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 89 },
   "targets": [
    {
     "expr": "ke_queries_scan_bytes{job=\"$job\",instance=\"$instance\",project=~\"$project\",quantile=\"0.9\"}/1048576",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "TOP10 Model AVG Build Minutes",
   "type": "bargauge",
   "description": "模型构建耗时top10的模型",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (model) (ke_model_build_minutes_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}) / sum by (model) (ke_model_build_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Metadata Connections",
   "type": "graph",
   "description": "元数据库连接数",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ke_db_connections{job=\"$job\",instance=\"$instance\",state=\"active\"}",
     "legendFormat": "active"
    },
    {
     "expr": "ke_db_connections{job=\"$job\",instance=\"$instance\",state=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "http_error_count(/api/models/.+/segments)",
   "type": "graph",
   "description": "模型构建Http接口失败次数统计",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\",uri=~\"/api/models/.+/segments\",method=\"POST\",status=~\"4..\"}[5m]))",
     "legendFormat": "http_status=4.."
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$job\",instance=\"$instance\",uri=~\"/api/models/.+/segments\",method=\"POST\",status=~\"5..\"}[5m]))",
     "legendFormat": "http_status=5.."
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "description": "Number Of Running Jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ke_job_counts{job=\"$job\",instance=\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Jobs Analyse",
   "type": "bargauge",
   "description": "Jobs Analyse",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ke_job_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range]))",
     "legendFormat": "job_totals"
    },
    {
     "expr": "sum(increase(ke_job_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"false\"}[$__range]))",
     "legendFormat": "job_fails"
    },
    {
     "expr": "sum(increase(ke_job_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\"}[$__range])) by (category)",
     "legendFormat": "jobs({{category}})"
    }
   ]
  },
  {
   "title": "Job Avg Duration",
   "type": "graph",
   "description": "Job Avg Duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ke_job_minutes_sum{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}[10m])) by (category) / sum(increase(ke_job_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}[10m])) by (category) ",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Jobs[5m]",
   "type": "timeseries",
   "description": "Number Of Jobs in last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ke_job_minutes_count{job=\"$job\",instance=\"$instance\",project=~\"$project\",succeed=\"true\"}[5m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  { "title": "HTTP Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Total number of requests",
   "type": "graph",
   "description": "http接口总请求频率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"$job\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "graph",
   "description": "http接口总耗时分析",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "graph",
   "description": "http请求最大耗时情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "graph",
   "description": "http接口平均耗时情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"$job\", instance=\"$instance\"}[4m]) / rate(http_server_requests_seconds_count{job=\"$job\", instance=\"$instance\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}