SELECT second(TEST_TIME_ENC) as h1, TEST_TIME_ENC, count(*) as cnt
 FROM TEST_KYLIN_FACT as TEST_KYLIN_FACT
 INNER JOIN TEST_ORDER as TEST_ORDER
 ON TEST_KYLIN_FACT.ORDER_ID = TEST_ORDER.ORDER_ID
 group by TEST_TIME_ENC
 order by TEST_TIME_ENC
