{
 "title": "Spark Executor Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{}, instance)"
    }
   },
   {
    "name": "applicationId",
    "label": "ApplicationId",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{instance=\"$instance\"},application_id)"
    }
   },
   {
    "name": "executorId",
    "label": "ExecutorId",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id!=\"driver\"},executor_id)"
    }
   },
   {
    "name": "selectExecutorNums",
    "label": "SelectExecutorNums",
    "query": "count(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id))"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Executors",
   "type": "stat",
   "description": "Total Executors",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id!=\"driver\"}) by (executor_id))"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "Total Number of cores available in this executor",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "stat",
   "description": "TotalT Number of tasks that have completed in this executor",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "description": "Failed Tasks",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_failedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Executing Tasks",
   "type": "stat",
   "description": "Total Number of tasks currently executing",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_activeTasks{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Total GC Time",
   "type": "stat",
   "description": "Total GC Time",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Total Duration",
   "type": "stat",
   "description": "Tasks Total Duration",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalDuration_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "gauge",
   "description": "Executor Memory Used",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id!=\"driver\"}) / sum(metrics_executor_maxMemory_bytes{application_id=\"$applicationId\", executor_id!=\"driver\"})"
    }
   ]
  },
  {
   "title": "Total Executor Memory",
   "type": "stat",
   "description": "Total Executor Memory",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_maxMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  {
   "title": "Total Rdd Blocks",
   "type": "stat",
   "description": "Total Rdd Blocks",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_rddBlocks{application_id=\"$applicationId\", executor_id=~\"$executorId\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Duration",
   "type": "bargauge",
   "description": "Total Duration Of Per Executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalDuration_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Duration[1m]",
   "type": "graph",
   "description": "Duration In Last 1 Minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_totalDuration_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])) \nby (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total GC Time",
   "type": "bargauge",
   "description": "Total  GC Time Of Per Executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalGCTime_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "GC Time[1m]",
   "type": "timeseries",
   "description": "GC Time In 1 Minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_totalGCTime_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Input",
   "type": "bargauge",
   "description": "Total input bytes of per executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalInputBytes_bytes_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Input[1m]",
   "type": "timeseries",
   "description": "Total input bytes of this executor in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_totalInputBytes_bytes_total{application_id=\"$applicationId\",executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Read",
   "type": "bargauge",
   "description": "Total shuffle read bytes summed in this executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalShuffleRead_bytes_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Read[1m]",
   "type": "timeseries",
   "description": "Total shuffle read bytes summed in this executor in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_totalShuffleRead_bytes_total{application_id=\"$applicationId\",executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Write",
   "type": "bargauge",
   "description": "Total shuffle write bytes summed in this executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalShuffleWrite_bytes_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id)",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Write[1m]",
   "type": "timeseries",
   "description": "Total shuffle write bytes summed in this executor in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_totalShuffleWrite_bytes_total{application_id=\"$applicationId\",executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory Used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "Total amount of memory available for storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_maxMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_maxMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Available Cores",
   "type": "graph",
   "description": "Number of cores available in this executor.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_totalCores{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_totalCores{application_id=\"$applicationId\", executor_id=~\"$executorId\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "description": "Disk space used for RDD storage by this executor",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_diskUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_diskUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Rdd Blocks",
   "type": "timeseries",
   "description": "RDD blocks in the block manager of this executor",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "metrics_executor_rddBlocks{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Completed Tasks",
   "type": "graph",
   "description": "Number of tasks that have completed in this executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_executor_completedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(increase(metrics_executor_completedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])) / count(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "graph",
   "description": "Number of tasks that have failed in this executor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_executor_failedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(increase(metrics_executor_failedTasks_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])) /\ncount(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Currently Executing Tasks",
   "type": "graph",
   "description": "Number of tasks currently executing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_activeTasks{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) /\ncount(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Concurrently Max Tasks",
   "type": "graph",
   "description": "Maximum number of tasks that can run concurrently in this executor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_maxTasks{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    },
    {
     "expr": "sum(metrics_executor_maxTasks{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) /\ncount(count(metrics_executor_memoryUsed_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}) by (executor_id))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Minor GC Rate",
   "type": "graph",
   "description": "minor GC rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_MinorGCCount_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Minor GC Time",
   "type": "timeseries",
   "description": "Elapsed total minor GC time. The value is expressed in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MinorGCTime_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Major GC Rate",
   "type": "graph",
   "description": "major GC rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_MajorGCCount_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Major GC Time",
   "type": "timeseries",
   "description": "Elapsed total major GC time. The value is expressed in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MajorGCTime_seconds_total{application_id=\"$applicationId\", executor_id=~\"$executorId\"}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  { "title": "Memory (Current) ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Used Heap Memory",
   "type": "timeseries",
   "description": "Used on heap memory currently for storage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_usedOnHeapStorageMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Used  Non-Heap Memory",
   "type": "timeseries",
   "description": "Used off heap memory currently for storage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_usedOffHeapStorageMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Available Heap Memory",
   "type": "timeseries",
   "description": "Total available on heap memory for storage, in bytes. This amount can vary over time, on the MemoryManager implementation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_totalOnHeapStorageMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Available Non-Heap Memory",
   "type": "timeseries",
   "description": "Total available off heap memory for storage, in bytes. This amount can vary over time, depending on the MemoryManager implementation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_totalOffHeapStorageMemory_bytes{application_id=\"$applicationId\", executor_id=~\"$executorId\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  }
 ]
}