{
 "title": "Spark Driver Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{},instance)"
    }
   },
   {
    "name": "applicationId",
    "label": "ApplicationId",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{instance=\"$instance\"},application_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver Memory Used",
   "type": "gauge",
   "description": "Driver Memory Used",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_driver_BlockManager_memory_memUsed_MB_Value{application_id=\"$applicationId\"}) / sum(metrics_driver_BlockManager_memory_maxMem_MB_Value{application_id=\"$applicationId\"})"
    }
   ]
  },
  {
   "title": "Total Driver Memory",
   "type": "stat",
   "description": "Total Driver Memory",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_driver_BlockManager_memory_maxMem_MB_Value{application_id=\"$applicationId\"}"
    }
   ]
  },
  {
   "title": "Waiting Stages",
   "type": "stat",
   "description": "Waiting Stages",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_driver_DAGScheduler_stage_waitingStages_Value{application_id=\"$applicationId\"}"
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "stat",
   "description": "Failed Stages",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_driver_DAGScheduler_stage_failedStages_Value{application_id=\"$applicationId\"}"
    }
   ]
  },
  {
   "title": "Running Stages",
   "type": "stat",
   "description": "Running Stages",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_driver_DAGScheduler_stage_runningStages_Value{application_id=\"$applicationId\"}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Jobs",
   "type": "graph",
   "description": "jobs_1m = jobs in last 1 minutes ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metrics_driver_DAGScheduler_job_allJobs_Value{application_id=\"$applicationId\"}[1m])",
     "legendFormat": "DAGScheduler_jobs_1m"
    },
    {
     "expr": "metrics_driver_DAGScheduler_job_activeJobs_Value{application_id=\"$applicationId\"}",
     "legendFormat": "DAGScheduler_activeJobs"
    }
   ]
  },
  {
   "title": "Stages",
   "type": "graph",
   "description": "Stages of DAGScheduler ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_driver_DAGScheduler_stage_runningStages_Value{application_id=\"$applicationId\"}",
     "legendFormat": "DAGScheduler_runningStages"
    },
    {
     "expr": "metrics_driver_DAGScheduler_stage_failedStages_Value{application_id=\"$applicationId\"}",
     "legendFormat": "DAGScheduler_failedStages"
    },
    {
     "expr": "metrics_driver_DAGScheduler_stage_waitingStages_Value{application_id=\"$applicationId\"}",
     "legendFormat": "DAGScheduler_waitingStages"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory space usage for driver",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "metrics_driver_BlockManager_memory_maxMem_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "maxMem"
    },
    {
     "expr": "metrics_driver_BlockManager_memory_maxOffHeapMem_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "maxOffHeapMem"
    },
    {
     "expr": "metrics_driver_BlockManager_memory_maxOnHeapMem_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "maxOnHeapMem"
    },
    {
     "expr": "metrics_driver_BlockManager_memory_memUsed_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "memUsed"
    },
    {
     "expr": "metrics_driver_BlockManager_memory_offHeapMemUsed_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "offHeapMemUsed"
    },
    {
     "expr": "metrics_driver_BlockManager_memory_onHeapMemUsed_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "onHeapMemUsed"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "description": "Disk space used for driver",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "metrics_driver_BlockManager_disk_diskSpaceUsed_MB_Value{application_id=\"$applicationId\"}",
     "legendFormat": "driver"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "MinorGCCount",
   "type": "timeseries",
   "description": "minor GC count in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MinorGCCount_total{application_id=\"$applicationId\", executor_id=\"driver\"}[1m])",
     "legendFormat": "MinorGCCount"
    }
   ]
  },
  {
   "title": "MinorGCTime",
   "type": "timeseries",
   "description": "minot GC duration in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MinorGCTime_seconds_total{application_id=\"$applicationId\", executor_id=\"driver\"}[1m])",
     "legendFormat": "MinorGCTime"
    }
   ]
  },
  {
   "title": "MajorGCCount",
   "type": "timeseries",
   "description": "major GC count in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MajorGCCount_total{application_id=\"$applicationId\", executor_id=\"driver\"}[1m])",
     "legendFormat": "MajorGCCount"
    }
   ]
  },
  {
   "title": "MajorGCTime",
   "type": "timeseries",
   "description": "major GC duration in last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(metrics_executor_MajorGCTime_seconds_total{application_id=\"$applicationId\", executor_id=\"driver\"}[1m])",
     "legendFormat": "MajorGCTime"
    }
   ]
  }
 ]
}