SELECT SUM(1) AS "COL"
FROM "POPHEALTH_ANALYTICS"."X_PROVIDER" "X_PROVIDER"
INNER JOIN "POPHEALTH_ANALYTICS"."X_PROVIDER" "X_PROVIDER1"
ON ("X_PROVIDER"."DEFAULT_PRACTICE" = "X_PROVIDER1"."DEFAULT_PRACTICE")
HAVING COUNT(1)>0;