-- equi join with non-equi joins
SELECT TEST_ACC.LEAF_CATEG_NAME, count(TEST_ACC.ACCOUNT_COUNTRY), sum(TEST_KYLIN_FACT.ITEM_COUNT)
FROM TEST_KYLIN_FACT
LEFT JOIN
(
  select TEST_ACCOUNT.ACCOUNT_ID as ACCOUNT_ID, TEST_ACCOUNT.ACCOUNT_COUNTRY as ACCOUNT_COUNTRY, TEST_CATEGORY_GROUPINGS.LEAF_CATEG_NAME as LEAF_CATEG_NAME
  FROM TEST_ACCOUNT
  LEFT JOIN TEST_CATEGORY_GROUPINGS
  ON TEST_CATEGORY_GROUPINGS.SITE_ID > 2
) TEST_ACC
ON TEST_KYLIN_FACT.SELLER_ID = TEST_ACC.ACCOUNT_ID
GROUP BY TEST_ACC.LEAF_CATEG_NAME
ORDER BY 1,2,3
LIMIT 10000