-- non-equi join with non-equi joins
SELECT TEST_CATEGORY_GROUPINGS.LEAF_CATEG_NAME, count(TEST_ACC.COUNTRY)
FROM
TEST_CATEGORY_GROUPINGS
LEFT JOIN
(
  select TEST_COUNTRY.COUNTRY as COUNTRY, ACCOUNT_BUYER_LEVEL, ACCOUNT_SELLER_LEVEL
  FROM TEST_COUNTRY
  LEFT JOIN TEST_ACCOUNT
  ON TEST_ACCOUNT.ACCOUNT_COUNTRY <> TEST_COUNTRY.COUNTRY
) TEST_ACC
ON
TEST_CATEGORY_GROUPINGS.LEAF_CATEG_NAME <> TEST_ACC.COUNTRY
AND TEST_CATEGORY_GROUPINGS.SITE_ID > 2
GROUP BY TEST_CATEGORY_GROUPINGS.LEAF_CATEG_NAME
ORDER BY 1,2
LIMIT 10000