SELECT TEST_ACCOUNT.ACCOUNT_SELLER_LEVEL, COUNT(TEST_COUNTRY.COUNTRY), SUM(TEST_ACCOUNT.ACCOUNT_BUYER_LEVEL)
FROM TEST_ACCOUNT
LEFT JOIN TEST_COUNTRY
ON
TEST_ACCOUNT.ACCOUNT_COUNTRY = TEST_COUNTRY.COUNTRY
AND TEST_ACCOUNT.ACCOUNT_BUYER_LEVEL > 3
GROUP BY TEST_ACCOUNT.ACCOUNT_SELLER_LEVEL
ORDER BY 1,2,3
LIMIT 10000