-- join with select
SELECT count(TEST_ACC.ACCOUNT_SELLER_LEVEL), TEST_ACC.ACCOUNT_BUYER_LEVEL
FROM
(
  select trim(ACCOUNT_COUNTRY) as ACCOUNT_COUNTRY, ACCOUNT_BUYER_LEVEL, ACCOUNT_SELLER_LEVEL
  FROM TEST_ACCOUNT
) TEST_ACC
LEFT JOIN
(
  SELECT trim(COUNTRY) as COUNTRY
  FROM TEST_COUNTRY
) TEST_COUNTRY
ON TEST_ACC.ACCOUNT_COUNTRY = TEST_COUNTRY.COUNTRY
and TEST_ACC.ACCOUNT_BUYER_LEVEL > 100
GROUP BY TEST_ACC.ACCOUNT_BUYER_LEVEL
ORDER BY 1,2
LIMIT 10000