-- runtime non-equi join
SELECT TEST_KYLIN_FACT.CAL_DT, sum(TEST_KYLIN_FACT.ITEM_COUNT)
FROM TEST_KYLIN_FACT
LEFT JOIN
(
  select ACCOUNT_ID, sum(ACCOUNT_BUYER_LEVEL)
  FROM TEST_ACCOUNT
  group by ACCOUNT_ID
) TEST_ACC
ON
TEST_KYLIN_FACT.SELLER_ID = TEST_ACC.ACCOUNT_ID
AND TEST_KYLIN_FACT.LSTG_FORMAT_NAME = 'FP-GTC'
GROUP BY TEST_KYLIN_FACT.CAL_DT, ACCOUNT_ID
ORDER BY 1,2
LIMIT 10000