-- non-equi join with equi joins, same first table
SELECT count(TEST_ACCOUNT.ACCOUNT_SELLER_LEVEL), TEST_ACCOUNT.ACCOUNT_BUYER_LEVEL
FROM
TEST_ACCOUNT
LEFT JOIN
(
  select TEST_COUNTRY.COUNTRY as COUNTRY, ACCOUNT_BUYER_LEVEL, ACCOUNT_SELLER_LEVEL
  FROM TEST_ACCOUNT
  LEFT JOIN TEST_COUNTRY
  ON TEST_ACCOUNT.ACCOUNT_COUNTRY = TEST_COUNTRY.COUNTRY
) TEST_ACC
ON
TEST_ACCOUNT.ACCOUNT_COUNTRY = TEST_ACC.COUNTRY
or TEST_ACCOUNT.ACCOUNT_BUYER_LEVEL > 100
GROUP BY TEST_ACCOUNT.ACCOUNT_BUYER_LEVEL
ORDER BY 1,2
LIMIT 10000