-- with agg pushdown
SELECT TEST_KYLIN_FACT.CAL_DT, sum(TEST_KYLIN_FACT.ITEM_COUNT)
FROM TEST_KYLIN_FACT
LEFT JOIN
(
  select ACCOUNT_ID, ACCOUNT_COUNTRY
  FROM TEST_ACCOUNT
  WHERE TEST_ACCOUNT.ACCOUNT_ID > 10000101
) TEST_ACC
ON
TEST_KYLIN_FACT.SELLER_ID = TEST_ACC.ACCOUNT_ID
AND TEST_KYLIN_FACT.LSTG_FORMAT_NAME = 'FP-GTC'
GROUP BY TEST_KYLIN_FACT.CAL_DT
ORDER BY 1,2
LIMIT 10000