-- test nested and or not
SELECT COUNT(1), TEST_KYLIN_FACT.SELLER_ID, TEST_ACCOUNT.ACCOUNT_ID, sum(TEST_KYLIN_FACT.ITEM_COUNT), count(TEST_ACCOUNT.ACCOUNT_CONTACT)
FROM TEST_KYLIN_FACT
LEFT JOIN TEST_ACCOUNT
ON
TEST_KYLIN_FACT.SELLER_ID = TEST_ACCOUNT.ACCOUNT_ID
OR TEST_KYLIN_FACT.LSTG_FORMAT_NAME='FP-GTC'
AND
(TEST_KYLIN_FACT.SELLER_ID <> TEST_ACCOUNT.ACCOUNT_ID)
AND (
TEST_KYLIN_FACT.PRICE > 100
AND (
TEST_KYLIN_FACT.ITEM_COUNT < 10
OR (NOT
TEST_KYLIN_FACT.PRICE * TEST_KYLIN_FACT.ITEM_COUNT > 500
)))
AND (not (not TEST_KYLIN_FACT.ITEM_COUNT < 10))
group by TEST_KYLIN_FACT.SELLER_ID, TEST_ACCOUNT.ACCOUNT_ID
order by 1,2,3,4,5
limit 10000
