select * from (
Select max(TEST_KYLIN_FACT.price),TEST_KYLIN_FACT.CAL_DT,TEST_KYLIN_FACT.ORDER_ID
From EDW.TEST_CAL_DT
Right  join TEST_KYLIN_FACT
On TEST_KYLIN_FACT.ORDER_ID > TEST_CAL_DT.AGE_FOR_YEAR_ID
Group by TEST_KYLIN_FACT.CAL_DT,TEST_KYLIN_FACT.ORDER_ID
order by TEST_KYLIN_FACT.CAL_DT desc ,TEST_KYLIN_FACT.ORDER_ID desc );

