--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

USE SSB;

drop table IF EXISTS CUSTOMER;

create EXTERNAL TABLE CUSTOMER (
C_CUSTKEY     INT,
C_NAME        string,
C_ADDRESS     string,
C_CITY        string,
C_NATION      string,
C_REGION      string,
C_PHONE       string,
C_MKTSEGMENT   string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

drop table IF EXISTS DATES;

create EXTERNAL TABLE DATES (
D_DATEKEY          DATE,
D_DATE             string,
D_DAYOFWEEK        string,
D_MONTH            string,
D_YEAR             INT,
D_YEARMONTHNUM     INT,
D_YEARMONTH        string,
D_DAYNUMINWEEK     INT,
D_DAYNUMINMONTH    INT,
D_DAYNUMINYEAR     INT,
D_MONTHNUMINYEAR   INT,
D_WEEKNUMINYEAR    INT,
D_SELLINGSEASON    string,
D_LASTDAYINWEEKFL  INT,
D_LASTDAYINMONTHFL INT,
D_HOLIDAYFL        INT,
D_WEEKDAYFL        INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

drop table IF EXISTS PART;

create EXTERNAL TABLE PART (
P_PARTKEY     INT,
P_NAME        string,
P_MFGR        string,
P_CATEGORY    string,
P_BRAND       string,
P_COLOR       string,
P_TYPE        string,
P_SIZE        INT,
P_CONTAINER   string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

drop table IF EXISTS SUPPLIER;

create EXTERNAL TABLE SUPPLIER (
S_SUPPKEY     INT,
S_NAME        string,
S_ADDRESS     string,
S_CITY        string,
S_NATION      string,
S_REGION      string,
S_PHONE       string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

drop table IF EXISTS LINEORDER;

create EXTERNAL TABLE LINEORDER (
LO_ORDERKEY       BIGINT,
LO_LINENUMBER     BIGINT,
LO_CUSTKEY        INT,
LO_PARTKEY        INT,
LO_SUPPKEY        INT,
LO_ORDERDATE      DATE,
LO_ORDERPRIOTITY  string,
LO_SHIPPRIOTITY   INT,
LO_QUANTITY       BIGINT,
LO_EXTENDEDPRICE  BIGINT,
LO_ORDTOTALPRICE  BIGINT,
LO_DISCOUNT       BIGINT,
LO_REVENUE        BIGINT,
LO_SUPPLYCOST     BIGINT,
LO_TAX            BIGINT,
LO_COMMITDATE     DATE,
LO_SHIPMODE       string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

drop view IF EXISTS P_LINEORDER;

create view P_LINEORDER as
select LO_ORDERKEY,
LO_LINENUMBER,
LO_CUSTKEY,
LO_PARTKEY,
LO_SUPPKEY,
LO_ORDERDATE,
LO_ORDERPRIOTITY,
LO_SHIPPRIOTITY,
LO_QUANTITY,
LO_EXTENDEDPRICE,
LO_ORDTOTALPRICE,
LO_DISCOUNT,
LO_REVENUE,
LO_SUPPLYCOST,
LO_TAX,
LO_COMMITDATE,
LO_SHIPMODE,
LO_EXTENDEDPRICE*LO_DISCOUNT as V_REVENUE
from LINEORDER;

LOAD DATA INPATH '${hdfs_tmp_dir}/sample_cube/data/SSB.CUSTOMER.csv' OVERWRITE INTO TABLE CUSTOMER;
LOAD DATA INPATH '${hdfs_tmp_dir}/sample_cube/data/SSB.DATES.csv' OVERWRITE INTO TABLE DATES;
LOAD DATA INPATH '${hdfs_tmp_dir}/sample_cube/data/SSB.LINEORDER.csv' OVERWRITE INTO TABLE LINEORDER;
LOAD DATA INPATH '${hdfs_tmp_dir}/sample_cube/data/SSB.PART.csv' OVERWRITE INTO TABLE PART;
LOAD DATA INPATH '${hdfs_tmp_dir}/sample_cube/data/SSB.SUPPLIER.csv' OVERWRITE INTO TABLE SUPPLIER;