select * from (
(select sum(ACCOUNT_BUYER_LEVEL), ACCOUNT_SELLER_LEVEL
from TEST_ACCOUNT
where ACCOUNT_COUNTRY='CN'
group by ACCOUNT_SELLER_LEVEL
)
EXCEPT
(select sum(ACCOUNT_SELLER_LEVEL), ACCOUNT_BUYER_LEVEL
from TEST_ACCOUNT
where ACCOUNT_COUNTRY='FR'
group by ACCOUNT_BUYER_LEVEL
)
)
